# Generated by Django 5.2.17 on 2026-08-24 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_owner_email_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerTOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_timestep', models.BigIntegerField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'owner TOTP device',
                'verbose_name_plural': 'owner TOTP devices',
            },
        ),
        migrations.CreateModel(
            name='OwnerRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'owner recovery code',
                'verbose_name_plural': 'owner recovery codes',
                'indexes': [models.Index(fields=['user', 'used_at'], name='owner_2fa_recov_user_used')],
            },
        ),
    ]
