# Generated by Django 5.2.17 on 2026-08-31 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ownertotpdevice_ownerrecoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAuthProviderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=16)),
                ('provider_subject', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(blank=True, default='', max_length=254)),
                ('provider_email_verified', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_provider_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'owner auth provider link',
                'verbose_name_plural': 'owner auth provider links',
                'indexes': [models.Index(fields=['user', 'provider'], name='owner_auth_link_user_prov')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='owner_auth_provider_subject_unique'), models.UniqueConstraint(fields=('user', 'provider'), name='owner_auth_provider_user_unique')],
            },
        ),
    ]
