# Generated by Django 5.2.17 on 2026-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_billing_market',
            field=models.CharField(blank=True, default='', help_text='Billing market captured from trusted geo at registration (global or jp). Applied when the Organization is provisioned. Not customer-mutable.', max_length=10),
        ),
    ]
