# Generated by Django 5.2.17 on 2026-09-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_owner_account_recovery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='owneraccountrecoverychallenge',
            new_name='accounts_ow_user_id_900472_idx',
            old_name='accounts_ow_user_id_7d3a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='owneraccountrecoverychallenge',
            new_name='accounts_ow_expires_a0d06d_idx',
            old_name='accounts_ow_expires_6c8f1b_idx',
        ),
        migrations.RenameIndex(
            model_name='owneraccountrecoveryevent',
            new_name='accounts_ow_user_id_84aca1_idx',
            old_name='accounts_ow_user_id_9f4c11_idx',
        ),
    ]
