import { useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, endpoints, fieldErrorsFromBody } from "@checkstation/api";
import { AuthLayout } from "../components/AuthLayout";
import { Alert, Button, Field, Input } from "../components/ui";
import { parseAccountLink, type AccountLink } from "../lib/accountLinks";
import { useApp } from "../lib/AppProvider";

type Stage = "link" | "reset" | "awaiting_two_factor" | "awaiting_credentials" | "awaiting_primary_verification" | "done";

export function EmailLinkPage() {
  const { api, auth, t } = useApp(); const navigate = useNavigate(); const lock = useRef(false);
  const [link, setLink] = useState(""); const [parsed, setParsed] = useState<AccountLink | null>(null); const [stage, setStage] = useState<Stage>("link"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [code, setCode] = useState(""); const [recovery, setRecovery] = useState(false); const [error, setError] = useState(""); const [fields, setFields] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false);
  async function recoveryStatus() { const result = await api.get<{ stage: string }>(endpoints.recoverAccountStatus()); if (["awaiting_two_factor", "awaiting_credentials", "awaiting_primary_verification"].includes(result.stage)) setStage(result.stage as Stage); else throw new Error(t("accountLink.expired")); }
  async function submit() { if (lock.current) return; lock.current = true; setBusy(true); setError(""); setFields({}); try { if (stage === "link") { const target = parseAccountLink(link); if (!target) throw new Error(t("accountLink.invalid")); setParsed(target); if (target.kind === "reset") { setStage("reset"); return; } await api.post(target.endpoint, { uid: target.uid, token: target.token }); setLink(""); if (target.kind === "recover") await recoveryStatus(); else { setStage("done"); await auth.bootstrap(); } } else if (stage === "reset" && parsed) { await api.post(parsed.endpoint, { uid: parsed.uid, token: parsed.token, password, password_confirm: confirmation }); setPassword(""); setConfirmation(""); setParsed(null); setStage("done"); } else if (stage === "awaiting_two_factor") { await api.post(endpoints.recoverAccountTwoFactor(), recovery ? { recovery_code: code } : { code }); setCode(""); await recoveryStatus(); } else if (stage === "awaiting_credentials") { await api.post(endpoints.recoverAccountComplete(), { email: email.trim(), password, password_confirm: confirmation }); setPassword(""); setConfirmation(""); setParsed(null); setStage("awaiting_primary_verification"); } } catch (caught) { if (caught instanceof ApiError) setFields(fieldErrorsFromBody(caught.data)); setError(caught instanceof Error ? caught.message : t("common.error")); } finally { lock.current = false; setBusy(false); } }
  const leadKey = stage === "link" ? "accountLink.hint" : stage === "awaiting_primary_verification" ? "accountLink.newEmailHint" : stage === "done" ? "accountLink.done" : "accountLink.continue";
  return <AuthLayout title={t("accountLink.title")} lead={t(leadKey)} footnote={<Link to="/sign-in">{t("auth.backToSignIn")}</Link>}><div className="form"><Alert>{error}</Alert>{stage === "link" ? <Field label={t("accountLink.link")}><Input autoFocus onChange={(event) => setLink(event.target.value)} type="url" value={link} /></Field> : null}{stage === "awaiting_credentials" ? <Field error={fields.email} label={t("auth.email")}><Input autoComplete="email" onChange={(event) => setEmail(event.target.value)} type="email" value={email} /></Field> : null}{stage === "reset" || stage === "awaiting_credentials" ? <><Field error={fields.password} label={t("security.newPassword")}><Input autoComplete="new-password" onChange={(event) => setPassword(event.target.value)} type="password" value={password} /></Field><Field error={fields.password_confirm} label={t("security.confirmPassword")}><Input autoComplete="new-password" onChange={(event) => setConfirmation(event.target.value)} type="password" value={confirmation} /></Field></> : null}{stage === "awaiting_two_factor" ? <><Field error={fields.code || fields.recovery_code} label={t(recovery ? "security.recoveryCode" : "security.code")}><Input autoComplete="one-time-code" onChange={(event) => setCode(event.target.value)} value={code} /></Field><Button onClick={() => { setRecovery((value) => !value); setCode(""); }} variant="secondary">{t(recovery ? "auth.useAuthenticator" : "auth.useRecovery")}</Button></> : null}{stage === "done" ? <Button onClick={() => navigate("/", { replace: true })}>{t("common.continue")}</Button> : stage === "awaiting_primary_verification" ? <Button onClick={() => { setStage("link"); setLink(""); }}>{t("accountLink.open")}</Button> : <Button loading={busy} onClick={() => void submit()}>{t("common.continue")}</Button>}</div></AuthLayout>;
}
