import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { endpoints } from "@checkstation/api";
import { canLaunchKiosk, canManageGroupConfiguration, hasPlanFeature, isGroupScopedStaff } from "@checkstation/domain";
import { Alert, Badge, Button, Card, DataRow, Empty, Field, Input, Loading, Modal, Page, PageHeader, Segmented, Select, Stat, Switch, TextArea, formatError } from "../components/ui";
import { useApp } from "../lib/AppProvider";
import { GroupClassesPanel } from "../components/GroupClassesPanel";

type Group = { id: number; name: string; status: string; group_type: string; participant_count: number; member_count: number; group_only_participant_count: number; section_count?: number; is_plan_locked: boolean; actions: { check_in_enabled: boolean; check_out_enabled: boolean; breaks_enabled: boolean; max_breaks: number | null }; participation: { email_required: boolean; pin_required: boolean }; forward_emails: string[]; readiness?: { setup_complete?: boolean }; };
type Participant = { id: number; group_participant_code?: string; member?: { name: string; email?: string }; name?: string; email?: string; effective?: { name?: string; email?: string }; overrides?: { name?: string; email?: string }; participation?: { emails?: string[]; has_pin?: boolean }; participation_emails?: string[]; _kind?: "member" | "visitor" };
type ClassRow = { id: number; name: string; participant_count?: number; status: string };
type Tab = "overview" | "participants" | "configuration" | "kiosk";

export function GroupDetailPage() {
  const { id } = useParams(); const { api, authState, t } = useApp(); const navigate = useNavigate();
  const [group, setGroup] = useState<Group | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("overview");
  const canConfigure = canManageGroupConfiguration(authState.session); const canParticipants = canConfigure || isGroupScopedStaff(authState.session);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(""); try { setGroup(await api.get<Group>(endpoints.group(id))); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setLoading(false); } }, [api, id, t]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <Page><Loading label={t("groups.loading")} /></Page>;
  if (!group || !id) return <Page><Alert>{error || t("common.error")}</Alert></Page>;
  const tabs: Array<{ value: Tab; label: string }> = [{ value: "overview", label: t("groups.overview") }, { value: "participants", label: t("groups.participantLabel") }];
  if (canConfigure && !group.is_plan_locked) tabs.push({ value: "configuration", label: t("groups.configuration") });
  if (!group.is_plan_locked && group.status !== "archived") tabs.push({ value: "kiosk", label: t("kiosk.title") });
  return <Page>
    <PageHeader eyebrow={t(group.group_type === "structured" ? "groups.structured" : "groups.standard")} title={group.name} actions={<Button variant="secondary" onClick={() => navigate("/groups")}>{t("groups.back")}</Button>} />
    <div className="toolbar"><Badge tone={group.status === "archived" ? "neutral" : "green"}>{t(group.status === "archived" ? "groups.archivedLabel" : "groups.activeLabel")}</Badge>{group.is_plan_locked ? <Badge tone="warning">{t("groups.planLocked")}</Badge> : null}{group.readiness && !group.readiness.setup_complete ? <Badge tone="warning">{t("groups.setupIncomplete")}</Badge> : null}</div>
    <Segmented value={tab} onChange={setTab} options={tabs} /><Alert>{error}</Alert>
    {tab === "overview" ? <Overview group={group} /> : null}
    {tab === "participants" ? <Participants group={group} groupId={id} canManage={canParticipants && !group.is_plan_locked && group.status !== "archived"} /> : null}
    {tab === "configuration" ? <Configuration group={group} groupId={id} onSaved={load} /> : null}
    {tab === "kiosk" ? <KioskManagement group={group} groupId={id} canLaunch={canLaunchKiosk(authState.session)} /> : null}
  </Page>;
}

function Overview({ group }: { group: Group }) {
  const { t } = useApp();
  return <><div className="stats"><Stat label={t("groups.participantLabel")} value={group.participant_count || 0} /><Stat label={t("members.title")} value={group.member_count || 0} tone="cyan" /><Stat label={group.group_type === "structured" ? t("groups.classes") : t("groups.visitors")} value={group.group_type === "structured" ? group.section_count || 0 : group.group_only_participant_count || 0} tone="green" /></div><div className="card-grid"><Card title={t("groups.actions")}><Summary label={t("kiosk.checkIn")} active={group.actions?.check_in_enabled} /><Summary label={t("kiosk.checkOut")} active={group.actions?.check_out_enabled} /><Summary label={t("kiosk.breaks")} active={group.actions?.breaks_enabled} /></Card><Card title={t("groups.participation")}><Summary label={t("groups.requireEmail")} active={group.participation?.email_required} /><Summary label={t("groups.requirePin")} active={group.participation?.pin_required} /></Card></div></>;
}
function Summary({ label, active }: { label: string; active?: boolean }) { const { t } = useApp(); return <div className="setting-row"><strong>{label}</strong><Badge tone={active ? "green" : "neutral"}>{t(active ? "security.enabled" : "security.notEnabled")}</Badge></div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="setting-row"><strong>{label}</strong><Switch checked={checked} onChange={onChange} label={label} /></div>; }

function Participants({ group, groupId, canManage }: { group: Group; groupId: string; canManage: boolean }) {
  const { api, t } = useApp(); const [rows, setRows] = useState<Participant[]>([]); const [classes, setClasses] = useState<ClassRow[]>([]); const [selectedClass, setSelectedClass] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Participant | null>(null); const [busy, setBusy] = useState(false);
  const scoped = selectedClass ? `${groupId}/classes/${selectedClass}` : groupId;
  const load = useCallback(async () => { setLoading(true); setError(""); try { if (group.group_type === "structured" && !selectedClass) { const data = await api.get<ClassRow[] | { results: ClassRow[] }>(endpoints.groupClasses(groupId)); setClasses(Array.isArray(data) ? data : data.results || []); setRows([]); } else { const [members, visitors] = await Promise.all([api.get<Participant[]>(endpoints.groupMemberships(scoped)), api.get<Participant[]>(endpoints.groupParticipants(scoped))]); setRows([...members.map((x) => ({ ...x, _kind: "member" as const })), ...visitors.map((x) => ({ ...x, _kind: "visitor" as const }))]); } } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setLoading(false); } }, [api, group.group_type, groupId, scoped, selectedClass, t]);
  useEffect(() => { void load(); }, [load]);
  async function remove(participant: Participant) { const name = participant.effective?.name || participant.member?.name || participant.name || ""; if (!confirm(t("groups.removeParticipantConfirm", { name }))) return; setBusy(true); setError(""); try { const path = participant._kind === "member" ? endpoints.groupMembership(scoped, participant.id) : endpoints.groupParticipant(scoped, participant.id); await api.delete(path); await load(); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  if (group.group_type === "structured" && !selectedClass) return <GroupClassesPanel groupId={groupId} canManage={canManage} onSelect={(section) => { setClasses([section]); setSelectedClass(String(section.id)); }} />;
  return <><Card title={selectedClass ? classes.find((x) => String(x.id) === selectedClass)?.name || t("groups.participantLabel") : t("groups.participantLabel")}><div className="toolbar">{selectedClass ? <Button variant="secondary" onClick={() => { setSelectedClass(""); setRows([]); }}>{t("classes.back")}</Button> : null}{canManage ? <Button onClick={() => setAdding(true)}>{t("groups.addParticipant")}</Button> : null}</div><Alert>{error}</Alert>{loading ? <Loading label={t("common.loading")} /> : rows.length ? <div className="data-list">{rows.map((p) => <DataRow key={`${p._kind}-${p.id}`} title={p.effective?.name || p.member?.name || p.name || "—"} detail={`${p._kind === "visitor" ? t("groups.visitor") : t("members.title")} · ${p.group_participant_code || "—"}`} meta={p.effective?.email || p.member?.email || p.email} actions={canManage ? <><Button className="button-sm" disabled={busy} onClick={() => setEditing(p)} variant="secondary">{t("common.edit")}</Button><Button className="button-sm" disabled={busy} onClick={() => void remove(p)} variant="danger">{t("common.remove")}</Button></> : undefined} />)}</div> : <Empty title={t("groups.noParticipants")} />}</Card>{adding ? <ParticipantCreate group={group} groupId={scoped} onClose={() => setAdding(false)} onSaved={() => { setAdding(false); void load(); }} /> : null}{editing ? <ParticipantEdit group={group} groupId={scoped} participant={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} /> : null}</>;
}

function ParticipantEdit({ group, groupId, participant, onClose, onSaved }: { group: Group; groupId: string; participant: Participant; onClose: () => void; onSaved: () => void }) {
  const { api, t } = useApp(); const visitor = participant._kind === "visitor"; const [name, setName] = useState(visitor ? participant.name || "" : participant.overrides?.name || ""); const [emails, setEmails] = useState((participant.participation?.emails || participant.participation_emails || []).join(", ")); const [pin, setPin] = useState(""); const [clearPin, setClearPin] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const body = new FormData(); if (visitor) body.append("name", name.trim()); else body.append("override_name", name.trim()); body.append("participation_emails", JSON.stringify(emails.split(/[\n,]/).map((value) => value.trim()).filter(Boolean))); if (pin) body.append("participation_pin", pin); if (clearPin) body.append("clear_participation_pin", "true"); const path = visitor ? endpoints.groupParticipant(groupId, participant.id) : endpoints.groupMembership(groupId, participant.id); await api.request(path, { method: "PATCH", formData: body }); onSaved(); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  const displayName = participant.effective?.name || participant.member?.name || participant.name || "";
  return <Modal title={t("groups.editParticipant")} onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>{t("common.cancel")}</Button><Button form="participant-edit" loading={busy} type="submit">{t("common.save")}</Button></>}><form className="form" id="participant-edit" onSubmit={submit}><Field label={visitor ? t("members.name") : t("groups.displayNameOverride")} hint={!visitor ? displayName : undefined}><Input required={visitor} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label={t("groups.participationEmails")} hint={group.participation.email_required ? t("groups.required") : t("groups.forwardEmailsPlaceholder")}><TextArea required={group.participation.email_required} value={emails} onChange={(event) => setEmails(event.target.value)} /></Field><Field label={t("kiosk.pin")} hint={participant.participation?.has_pin ? t("groups.pinChangeHint") : t("groups.optionalPin")}><Input disabled={clearPin} type="password" value={pin} onChange={(event) => setPin(event.target.value)} /></Field>{participant.participation?.has_pin ? <label className="check-row"><span>{t("groups.clearPin")}</span><input checked={clearPin} onChange={(event) => { setClearPin(event.target.checked); if (event.target.checked) setPin(""); }} type="checkbox" /></label> : null}<Alert>{error}</Alert></form></Modal>;
}

function ParticipantCreate({ group, groupId, onClose, onSaved }: { group: Group; groupId: string; onClose: () => void; onSaved: () => void }) {
  const { api, t } = useApp(); const [mode, setMode] = useState<"member" | "visitor">("member"); const [available, setAvailable] = useState<Array<{ id: number; name: string; email?: string }>>([]); const [memberId, setMemberId] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [pin, setPin] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (mode === "member") void api.get<Array<{ id: number; name: string; email?: string }>>(endpoints.groupAvailableMembers(groupId)).then(setAvailable).catch((caught) => setError(formatError(caught, t("common.error")))); }, [api, groupId, mode, t]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (mode === "member") await api.post(endpoints.groupMemberships(groupId), { member_id: Number(memberId), ...(pin ? { participation_pin: pin } : {}) }); else await api.post(endpoints.groupParticipants(groupId), { name: name.trim(), email: email.trim(), ...(pin ? { participation_pin: pin } : {}) }); onSaved(); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  return <Modal title={t("groups.addParticipant")} onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>{t("common.cancel")}</Button><Button loading={busy} type="submit" form="participant-create">{t("groups.addParticipant")}</Button></>}><form id="participant-create" className="form" onSubmit={submit}><Segmented value={mode} onChange={setMode} options={[{ value: "member", label: t("members.title") }, { value: "visitor", label: t("groups.visitor") }]} />{mode === "member" ? <Field label={t("groups.selectMember")}><Select required value={memberId} onChange={(e) => setMemberId(e.target.value)}><option value="">{t("groups.selectMember")}</option>{available.map((m) => <option key={m.id} value={m.id}>{m.name}{m.email ? ` · ${m.email}` : ""}</option>)}</Select></Field> : <><Field label={t("members.name")}><Input required value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label={t("auth.email")}><Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field></>}<Field label={t("kiosk.pin")} hint={group.participation.pin_required ? t("groups.required") : t("groups.optionalPin")}><Input type="password" value={pin} onChange={(e) => setPin(e.target.value)} /></Field><Alert>{error}</Alert></form></Modal>;
}

function Configuration({ group, groupId, onSaved }: { group: Group; groupId: string; onSaved: () => Promise<void> }) {
  const { api, authState, t } = useApp(); const [name, setName] = useState(group.name); const [actions, setActions] = useState(group.actions); const [participation, setParticipation] = useState(group.participation); const [forward, setForward] = useState((group.forward_emails || []).join("\n")); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const forwardAllowed = hasPlanFeature(authState.session, "group_forward_emails");
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { await api.patch(endpoints.group(groupId), { name: name.trim(), actions, participation, advanced: { forward_emails: forward.split(/[\n,]/).map((x) => x.trim()).filter(Boolean) } }); setMessage(t("groups.settingsSaved")); await onSaved(); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  async function lifecycle() { if (!confirm(t(group.status === "archived" ? "groups.restoreHint" : "groups.archiveConfirm"))) return; setBusy(true); try { await api.post(group.status === "archived" ? endpoints.groupRestore(groupId) : endpoints.groupArchive(groupId), {}); await onSaved(); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  return <form className="section-grid" onSubmit={save}><div className="form"><Alert>{error}</Alert><Alert tone="success">{message}</Alert><Card title={t("groups.groupSection")}><Field label={t("groups.name")}><Input required value={name} onChange={(e) => setName(e.target.value)} /></Field></Card><Card title={t("groups.actions")}><Toggle label={t("kiosk.checkIn")} checked={actions.check_in_enabled} onChange={(v) => setActions({ ...actions, check_in_enabled: v })} /><Toggle label={t("kiosk.checkOut")} checked={actions.check_out_enabled} onChange={(v) => setActions({ ...actions, check_out_enabled: v })} /><Toggle label={t("kiosk.breaks")} checked={actions.breaks_enabled} onChange={(v) => setActions({ ...actions, breaks_enabled: v })} /></Card><Card title={t("groups.participation")}><Toggle label={t("groups.requireEmail")} checked={participation.email_required} onChange={(v) => setParticipation({ ...participation, email_required: v })} /><Toggle label={t("groups.requirePin")} checked={participation.pin_required} onChange={(v) => setParticipation({ ...participation, pin_required: v })} /></Card><Card title={t("groups.notifications")}><Field label={t("groups.forwardEmails")} hint={forwardAllowed ? t("groups.forwardEmailsHint") : t("groups.forwardEmailsLockedHint")}><TextArea disabled={!forwardAllowed} value={forward} onChange={(e) => setForward(e.target.value)} placeholder={t("groups.forwardEmailsPlaceholder")} /></Field></Card><Button type="submit" loading={busy}>{t("groups.saveChanges")}</Button></div><Card className="danger-zone" title={t("groups.dangerZone")} description={t(group.status === "archived" ? "groups.restoreHint" : "groups.archiveHint")}><Button variant="danger" type="button" loading={busy} onClick={() => void lifecycle()}>{t(group.status === "archived" ? "groups.restore" : "groups.archive")}</Button></Card></form>;
}

function KioskManagement({ group, groupId, canLaunch }: { group: Group; groupId: string; canLaunch: boolean }) {
  const { api, t } = useApp(); const navigate = useNavigate(); const [settings, setSettings] = useState<Record<string, unknown> | null>(null); const [design, setDesign] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([api.get<Record<string, unknown>>(endpoints.kioskSettings(groupId)), api.get<Record<string, unknown>>(endpoints.kioskDesign(groupId))]).then(([s,d]) => { setSettings(s); setDesign(d); }).catch((caught) => setError(formatError(caught, t("common.error")))); }, [api, groupId, t]);
  return <div className="card-grid"><Card title={t("kiosk.settings")} description={t("kiosk.modeHint")}><p className="muted-copy">{settings ? `${t("kiosk.mode")}: ${String(settings.kiosk_mode || settings.mode || "—")}` : t("kiosk.notConfigured")}</p><div className="card-action"><Badge tone={settings ? "green" : "neutral"}>{settings ? t("kiosk.configured") : t("kiosk.notConfigured")}</Badge><Button variant="secondary" onClick={() => navigate(`/groups/${groupId}/kiosk-settings`)}>{t("common.edit")}</Button></div></Card><Card title={t("kiosk.design")} description={t("kiosk.designDescription")}><p className="muted-copy">{design ? t("kiosk.configured") : t("kiosk.notConfigured")}</p><div className="card-action"><Button variant="secondary" onClick={() => navigate(`/groups/${groupId}/kiosk-design`)}>{t("common.edit")}</Button>{canLaunch ? <Button onClick={() => navigate(`/kiosk/${groupId}`)}>{t("kiosk.open")}</Button> : null}</div></Card></div>;
}
