import { Fragment, useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation } from "react-router-dom";
import { createAppConfig } from "@checkstation/config";
import { formatDateTime } from "@checkstation/i18n";
import { Alert, Badge, Button, Card, DataRow, Empty, Input, Loading, Page, PageHeader, Segmented, formatError } from "../components/ui";
import { getDocument, getDocuments, getFaq, getStatus, type Document, type DocumentSummary, type Faq, type StatusSnapshot } from "../lib/help";
import { useApp } from "../lib/AppProvider";
type View = "resources" | "faq" | "status";

export function HelpPage() {
  const { api, locale, t } = useApp(); const location = useLocation(); const [view, setView] = useState<View>((location.state as { view?: View } | null)?.view || "resources"); const [docs, setDocs] = useState<DocumentSummary[]>([]); const [faqs, setFaqs] = useState<Faq[]>([]); const [categories, setCategories] = useState<Array<{ id: string; label: string }>>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [article, setArticle] = useState<Document | null>(null); const [expanded, setExpanded] = useState(""); const [status, setStatus] = useState<StatusSnapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const statusBase = useMemo(() => createAppConfig({ apiBaseUrl: import.meta.env.VITE_API_BASE_URL || "https://workspace.checkstation.app/api" }).statusBaseUrl, []);
  const loadContent = useCallback(async () => { setLoading(true); setError(""); try { const [docData, faqData] = await Promise.all([getDocuments(api, locale), getFaq(api, locale, category, search)]); setDocs(docData.documents || []); setFaqs(faqData.entries || []); setCategories(faqData.categories || []); } catch (caught) { setError(formatError(caught, t("help.contentError"))); } finally { setLoading(false); } }, [api, category, locale, search, t]);
  const loadStatus = useCallback(async () => { setLoading(true); setError(""); try { setStatus(await getStatus(statusBase, locale)); } catch (caught) { setError(formatError(caught, t("status.error"))); } finally { setLoading(false); } }, [locale, statusBase, t]);
  useEffect(() => { if (view === "status") void loadStatus(); else void loadContent(); }, [loadContent, loadStatus, view]);
  async function openArticle(slug: string) { setLoading(true); setError(""); try { setArticle(await getDocument(api, slug, locale)); } catch (caught) { setError(formatError(caught, t("help.articleError"))); } finally { setLoading(false); } }
  if (article) return <Page narrow><PageHeader eyebrow={article.nav_group_label || t("help.article")} title={article.title} description={article.description} actions={<Button variant="secondary" onClick={() => setArticle(null)}>{t("common.back")}</Button>} />{article.fallback ? <Alert tone="info">{t("help.translationFallback")}</Alert> : null}<div className="toolbar">{article.version ? <Badge tone="blue">{t("help.version")} {article.version}</Badge> : null}{article.updated_at ? <span className="muted-copy">{t("help.updated")} {formatDateTime(article.updated_at, locale)}</span> : null}</div><Card><Markdown markdown={article.body_markdown} onDocument={(slug) => void openArticle(slug)} /></Card></Page>;
  return <Page><PageHeader title={t("help.title")} description={t("help.hubDescription")} /><Segmented value={view} onChange={setView} options={[{ value: "resources", label: t("help.resources") }, { value: "faq", label: t("help.faqTitle") }, { value: "status", label: t("status.title") }]} /><Alert>{error}</Alert>{view === "resources" ? <Resources docs={docs} loading={loading} onOpen={openArticle} /> : view === "faq" ? <FaqView entries={faqs} categories={categories} category={category} expanded={expanded} search={search} loading={loading} onCategory={setCategory} onExpanded={setExpanded} onSearch={setSearch} onDocument={openArticle} /> : <StatusView snapshot={status} loading={loading} onRefresh={loadStatus} />}</Page>;
}
function Resources({ docs, loading, onOpen }: { docs: DocumentSummary[]; loading: boolean; onOpen: (slug: string) => void }) { const { t } = useApp(); const grouped = docs.reduce<Record<string, DocumentSummary[]>>((all, doc) => { (all[doc.nav_group_label || doc.document_type] ||= []).push(doc); return all; }, {}); if (loading) return <Loading label={t("help.loadingContent")} />; if (!docs.length) return <Empty title={t("help.emptyTitle")} body={t("help.emptyBody")} />; return <div className="card-grid">{Object.entries(grouped).map(([group, items]) => <Card title={group} key={group}><div className="data-list">{items.map((doc) => <DataRow key={doc.id} title={doc.title} detail={doc.description} badge={doc.version ? <Badge tone="blue">v{doc.version}</Badge> : undefined} onClick={() => onOpen(doc.slug)} />)}</div></Card>)}</div>; }
function FaqView({ entries, categories, category, expanded, search, loading, onCategory, onExpanded, onSearch, onDocument }: { entries: Faq[]; categories: Array<{ id: string; label: string }>; category: string; expanded: string; search: string; loading: boolean; onCategory: (v: string) => void; onExpanded: (v: string) => void; onSearch: (v: string) => void; onDocument: (slug: string) => void }) { const { t } = useApp(); return <><div className="toolbar"><Input className="input search" value={search} onChange={(e) => onSearch(e.target.value)} placeholder={t("help.searchFaq")} /><select className="input faq-category" value={category} onChange={(e) => onCategory(e.target.value)}><option value="">{t("help.allCategories")}</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.label}</option>)}</select></div>{loading ? <Loading label={t("help.loadingContent")} /> : entries.length ? <div className="faq-list">{entries.map((faq) => <Card key={faq.id} className="faq-card"><button className="faq-question" type="button" onClick={() => onExpanded(expanded === faq.id ? "" : faq.id)}><strong>{faq.question}</strong><span>{expanded === faq.id ? "−" : "+"}</span></button>{expanded === faq.id ? <div className="faq-answer"><Markdown markdown={faq.answer_markdown} onDocument={onDocument} />{faq.related_document_slug ? <Button variant="secondary" onClick={() => onDocument(faq.related_document_slug!)}>{t("help.openRelatedGuide")}</Button> : null}</div> : null}</Card>)}</div> : <Empty title={t("help.noFaqResults")} />}</>; }
function StatusView({ snapshot, loading, onRefresh }: { snapshot: StatusSnapshot | null; loading: boolean; onRefresh: () => Promise<void> }) { const { locale, t } = useApp(); if (loading) return <Loading label={t("status.loading")} />; const grouped = (snapshot?.current.components || []).reduce<Record<string, StatusSnapshot["current"]["components"]>>((all, item) => { (all[item.layer] ||= []).push(item); return all; }, {}); return <><Card><div className="status-overall"><div><span>{t("status.overall")}</span><strong>{snapshot?.current.overall.label || t("status.notChecked")}</strong>{snapshot?.current.last_checked_at ? <small>{t("status.lastChecked")} {formatDateTime(snapshot.current.last_checked_at, locale)}</small> : null}</div><Badge tone={snapshot?.current.overall.state === "operational" ? "green" : "warning"}>{snapshot?.current.overall.label || "—"}</Badge><Button variant="secondary" onClick={() => void onRefresh()}>{t("status.refresh")}</Button></div></Card><div className="card-grid">{Object.entries(grouped).map(([layer, components]) => <Card title={t(`status.layer.${["core","supporting","peripheral"].includes(layer) ? layer : "other"}`)} key={layer}><div className="data-list">{components.map((component) => <DataRow key={component.id} title={component.name} detail={component.description} badge={<Badge tone={component.state === "operational" ? "green" : "warning"}>{component.label}</Badge>} />)}</div></Card>)}</div><Card title={t("status.activeIncidents")}><>{snapshot?.incidents.active.length ? snapshot.incidents.active.map((incident) => <Alert key={incident.id} tone="warning"><strong>{incident.title}</strong><br />{incident.summary}</Alert>) : <Empty title={t("status.noActiveIncidents")} />}</></Card><Card title={t("status.maintenance")}><>{snapshot?.maintenance.windows.length ? snapshot.maintenance.windows.map((window) => <DataRow key={window.id} title={window.title} detail={window.note} meta={window.starts_at} />) : <Empty title={t("status.noMaintenance")} />}</></Card></>; }

function Markdown({ markdown, onDocument }: { markdown: string; onDocument: (slug: string) => void }) {
  const blocks: ReactNode[] = []; const lines = String(markdown || "").replace(/\r\n/g, "\n").split("\n"); let paragraph: string[] = []; const flush = () => { if (!paragraph.length) return; blocks.push(<p key={blocks.length}>{inline(paragraph.join(" "), onDocument)}</p>); paragraph = []; };
  for (const line of lines) { if (!line.trim()) { flush(); continue; } const heading = /^(#{1,4})\s+(.+)$/.exec(line); if (heading) { flush(); const Tag = heading[1].length < 3 ? "h2" : "h3"; blocks.push(<Tag key={blocks.length}>{inline(heading[2], onDocument)}</Tag>); continue; } const item = /^\s*(?:[-*]|\d+\.)\s+(.+)$/.exec(line); if (item) { flush(); blocks.push(<div className="markdown-list-row" key={blocks.length}><span>•</span><p>{inline(item[1], onDocument)}</p></div>); continue; } if (line.startsWith(">")) { flush(); blocks.push(<blockquote key={blocks.length}>{inline(line.replace(/^>\s?/, ""), onDocument)}</blockquote>); continue; } paragraph.push(line.trim()); } flush(); return <div className="markdown">{blocks}</div>;
}
function inline(text: string, onDocument: (slug: string) => void) { const output: ReactNode[] = []; const token = /(\[[^\]]+\]\([^)]+\)|\*\*[^*]+\*\*|\`[^\`]+\`)/g; let cursor = 0; for (const [index, match] of [...text.matchAll(token)].entries()) { if ((match.index || 0) > cursor) output.push(text.slice(cursor, match.index)); const value = match[0]; if (value.startsWith("**")) output.push(<strong key={index}>{value.slice(2,-2)}</strong>); else if (value.startsWith("`")) output.push(<code key={index}>{value.slice(1,-1)}</code>); else { const link = /^\[([^\]]+)\]\(([^)]+)\)$/.exec(value); const href = link?.[2] || ""; if (/^\/[a-z0-9-]+$/i.test(href)) output.push(<button className="markdown-link" type="button" key={index} onClick={() => onDocument(href.slice(1))}>{link?.[1]}</button>); else output.push(<a key={index} href={href} target="_blank" rel="noreferrer">{link?.[1]}</a>); } cursor = (match.index || 0) + value.length; } if (cursor < text.length) output.push(text.slice(cursor)); return <>{output.map((node, i) => <Fragment key={i}>{node}</Fragment>)}</>; }
