import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ApiError, endpoints, fieldErrorsFromBody } from "@checkstation/api";
import { canManageWorkspace, canViewGlobalMembers } from "@checkstation/domain";
import { Alert, Badge, Button, Card, Field, Input, Loading, Page, PageHeader, TextArea, formatError } from "../components/ui";
import { AuthenticatedImage } from "../components/AuthenticatedImage";
import { useApp } from "../lib/AppProvider";

type Member = { id: number; name: string; email?: string; phone?: string; address?: string; notes?: string; date_of_birth?: string | null; status?: string; check_in_identifier?: string; photo_url?: string | null; is_plan_locked?: boolean };
export function MemberDetailPage() {
  const { id = "" } = useParams(); const { api, authState, t } = useApp(); const navigate = useNavigate(); const [member, setMember] = useState<Member | null>(null); const [values, setValues] = useState<Record<string, string>>({}); const [photo, setPhoto] = useState<File | null>(null); const [clearPhoto, setClearPhoto] = useState(false); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [fields, setFields] = useState<Record<string, string>>({}); const canManage = canManageWorkspace(authState.session);
  const load = useCallback(async () => { setLoading(true); try { const value = await api.get<Member>(endpoints.member(id)); setMember(value); setValues(Object.fromEntries(["name", "email", "phone", "date_of_birth", "address", "notes"].map((key) => [key, String((value as unknown as Record<string, unknown>)[key] || "")]))); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setLoading(false); } }, [api, id, t]); useEffect(() => { if (canViewGlobalMembers(authState.session)) void load(); }, [authState.session, load]);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setFields({}); try { const body = new FormData(); Object.entries(values).forEach(([key, value]) => body.append(key, value.trim())); if (photo) body.append("photo", photo); if (clearPhoto) body.append("clear_photo", "true"); const saved = await api.request<Member>(endpoints.member(id), { method: "PATCH", formData: body }); setMember(saved); setPhoto(null); setClearPhoto(false); setEditing(false); } catch (caught) { if (caught instanceof ApiError) setFields(fieldErrorsFromBody(caught.data)); setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  async function mutate(action: "archive" | "restore" | "permanently-delete") { if (!member || !window.confirm(t(action === "archive" ? "members.archiveConfirm" : action === "permanently-delete" ? "members.deleteConfirm" : "members.restore" , { name: member.name }))) return; setBusy(true); try { const result = await api.post<Member>(`${endpoints.member(id)}${action}/`, {}); if (action === "permanently-delete") navigate("/people"); else { setMember(result); await load(); } } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  if (loading) return <Page><Loading label={t("members.loading")} /></Page>; if (!member) return <Page><Alert>{error}</Alert></Page>;
  const fieldsList = ["name", "email", "phone", "date_of_birth", "address", "notes"] as const;
  return <Page narrow><PageHeader actions={canManage && member.status !== "archived" && !member.is_plan_locked ? <Button onClick={() => setEditing((value) => !value)} variant="secondary">{editing ? t("common.cancel") : t("members.edit")}</Button> : undefined} description={member.email || member.phone} title={member.name} /><div className="member-heading"><span className="profile-photo">{member.photo_url ? <AuthenticatedImage alt="" src={member.photo_url} /> : null}<span className="avatar-fallback">{member.name.slice(0, 1).toUpperCase()}</span></span><Badge tone={member.status === "archived" ? "neutral" : member.is_plan_locked ? "warning" : "green"}>{member.is_plan_locked ? t("members.planLocked") : member.status === "archived" ? t("members.archivedLabel") : t("members.active")}</Badge></div><Alert>{error}</Alert>{editing ? <Card title={t("members.edit")}><form className="form" onSubmit={save}><Field error={fields.photo} label={t("members.choosePhoto")}><Input accept="image/*" onChange={(event) => { setPhoto(event.target.files?.[0] || null); setClearPhoto(false); }} type="file" />{member.photo_url && !clearPhoto ? <Button onClick={() => { setPhoto(null); setClearPhoto(true); }} variant="ghost">{t("members.removePhoto")}</Button> : null}</Field>{fieldsList.map((key) => <Field error={fields[key]} key={key} label={t(key === "email" ? "auth.email" : key === "date_of_birth" ? "members.birthday" : `members.${key}`)}>{key === "notes" || key === "address" ? <TextArea onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} value={values[key]} /> : <Input onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} type={key === "email" ? "email" : key === "date_of_birth" ? "date" : "text"} value={values[key]} />}</Field>)}<Button loading={busy} type="submit">{t("members.save")}</Button></form></Card> : <Card title={t("members.contactDetails")}><dl className="info-grid">{[[t("auth.email"), member.email], [t("members.phone"), member.phone], [t("members.identifier"), member.check_in_identifier], [t("members.birthday"), member.date_of_birth], [t("members.address"), member.address], [t("members.notes"), member.notes]].map(([label, value]) => <div className="info-item" key={String(label)}><dt>{label}</dt><dd>{value || "—"}</dd></div>)}</dl></Card>}{canManage ? <Card className="danger-zone" description={t("members.archiveConfirm", { name: member.name })} title={t("groups.dangerZone")}>{member.status === "archived" ? <div className="page-actions"><Button loading={busy} onClick={() => void mutate("restore")}>{t("members.restore")}</Button><Button loading={busy} onClick={() => void mutate("permanently-delete")} variant="danger">{t("members.delete")}</Button></div> : <Button loading={busy} onClick={() => void mutate("archive")} variant="danger">{t("members.archive")}</Button>}</Card> : null}</Page>;
}
