import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ApiError, endpoints, fieldErrorsFromBody } from "@checkstation/api";
import { canManageOwnerAccount } from "@checkstation/domain";
import { Alert, Badge, Button, Card, DataRow, Field, Input, Loading, Modal, Page, PageHeader, Segmented, formatError } from "../components/ui";
import { useApp } from "../lib/AppProvider";

type Account = { two_factor_status?: string; sign_in_methods?: { password?: { enabled?: boolean }; google?: { linked?: boolean; provider_email?: string | null }; apple?: { linked?: boolean; provider_email?: string | null } } };
type Action = "password" | "setup" | "regenerate" | "disable";

export function SecurityPage() {
  const { api, authState, t } = useApp(); const allowed = canManageOwnerAccount(authState.session); const [account, setAccount] = useState<Account | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [action, setAction] = useState<Action | null>(null);
  const load = useCallback(async () => { if (!allowed) return; setLoading(true); setError(""); try { setAccount(await api.get<Account>(endpoints.account())); } catch (caught) { setError(formatError(caught, t("common.error"))); } finally { setLoading(false); } }, [allowed, api, t]);
  useEffect(() => { void load(); }, [load]);
  if (!allowed) return <Page><Alert tone="warning">{t("more.staffRoleDescription")}</Alert></Page>;
  if (loading) return <Page><Loading label={t("security.loading")} /></Page>;
  const methods = account?.sign_in_methods; const enabled = account?.two_factor_status === "enabled"; const password = Boolean(methods?.password?.enabled);
  return <Page narrow><PageHeader title={t("nav.security")} description={t("security.description")} /><Alert>{error}</Alert><Card title={t("security.twoFactor")}><DataRow title={t("security.authenticator")} detail={enabled ? t("security.enabled") : t("security.notEnabled")} badge={<Badge tone={enabled ? "green" : "neutral"}>{t(enabled ? "security.enabled" : "security.notEnabled")}</Badge>} actions={password ? enabled ? <><Button className="button-sm" variant="secondary" onClick={() => setAction("regenerate")}>{t("security.regenerate")}</Button><Button className="button-sm" variant="danger" onClick={() => setAction("disable")}>{t("security.disable")}</Button></> : <Button className="button-sm" onClick={() => setAction("setup")}>{t("security.setup")}</Button> : undefined} /></Card><Card title={t("security.signInMethods")}><Method title={t("security.password")} enabled={password} detail={password ? undefined : t("security.passwordUnavailable")} /><Method title="Google" enabled={Boolean(methods?.google?.linked)} detail={methods?.google?.provider_email || undefined} /><Method title="Apple" enabled={Boolean(methods?.apple?.linked)} detail={methods?.apple?.provider_email || undefined} /></Card>{password ? <Button variant="secondary" onClick={() => setAction("password")}>{t("security.changePassword")}</Button> : <Alert tone="info">{t("security.passwordUnavailable")}</Alert>}{action ? <SecurityModal action={action} onClose={() => setAction(null)} onSaved={() => { setAction(null); void load(); }} /> : null}</Page>;
}
function Method({ title, enabled, detail }: { title: string; enabled: boolean; detail?: string }) { const { t } = useApp(); return <DataRow title={title} detail={detail} badge={<Badge tone={enabled ? "green" : "neutral"}>{t(enabled ? "security.enabled" : "security.notEnabled")}</Badge>} />; }

function SecurityModal({ action, onClose, onSaved }: { action: Action; onClose: () => void; onSaved: () => void }) {
  const { api, t } = useApp(); const [password, setPassword] = useState(""); const [next, setNext] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [code, setCode] = useState(""); const [codeType, setCodeType] = useState<"code" | "recovery_code">("code"); const [setup, setSetup] = useState<{ setup_key: string; qr_data_uri: string } | null>(null); const [codes, setCodes] = useState<string[] | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [fields, setFields] = useState<Record<string, string>>({});
  const title = t(action === "password" ? "security.changePassword" : `security.${action}`);
  async function submit(event?: FormEvent) { event?.preventDefault(); setBusy(true); setError(""); setFields({}); try { if (action === "password") { await api.post(endpoints.changePassword(), { current_password: password, new_password: next, new_password_confirm: confirmPassword }); onSaved(); } else if (action === "setup" && !setup) { setSetup(await api.post(endpoints.ownerTwoFactorSetup(), { current_password: password })); setPassword(""); } else if (action === "setup") { const result = await api.post<{ recovery_codes: string[] }>(endpoints.ownerTwoFactorVerify(), { code }); setCodes(result.recovery_codes || []); } else { const result = await api.post<{ recovery_codes?: string[] }>(action === "regenerate" ? endpoints.ownerTwoFactorRegenerate() : endpoints.ownerTwoFactorDisable(), { current_password: password, [codeType]: code }); if (action === "regenerate") setCodes(result.recovery_codes || []); else onSaved(); } } catch (caught) { if (caught instanceof ApiError) setFields(fieldErrorsFromBody(caught.data)); setError(formatError(caught, t("common.error"))); } finally { setBusy(false); } }
  if (codes) return <Modal title={t("security.recoveryCodes")} onClose={onClose} actions={<Button onClick={onSaved}>{t("security.done")}</Button>}><Alert tone="warning">{t("security.codesHint")}</Alert><pre className="code-block recovery-codes">{codes.join("\n")}</pre></Modal>;
  return <Modal title={title} onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>{t("common.cancel")}</Button><Button variant={action === "disable" ? "danger" : "primary"} form="security-form" type="submit" loading={busy}>{setup ? t("auth.verify") : title}</Button></>}><form id="security-form" className="form" onSubmit={submit}><Alert>{error}</Alert>{!setup ? <Field label={t("security.currentPassword")} error={fields.current_password}><Input autoFocus required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></Field> : null}{action === "password" ? <><Field label={t("security.newPassword")} error={fields.new_password}><Input required type="password" value={next} onChange={(e) => setNext(e.target.value)} /></Field><Field label={t("security.confirmPassword")} error={fields.new_password_confirm}><Input required type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /></Field></> : null}{setup ? <><p className="muted-copy">{t("security.setupHint")}</p><img className="qr-code" src={setup.qr_data_uri} alt={t("security.setupKey")} /><code className="setup-key">{setup.setup_key}</code></> : null}{setup || action === "regenerate" || action === "disable" ? <><Segmented value={codeType} onChange={setCodeType} options={[{ value: "code", label: t("auth.authenticatorCode") }, { value: "recovery_code", label: t("auth.recoveryCode") }]} /><Field label={t(codeType === "code" ? "security.code" : "security.recoveryCode")} error={fields[codeType]}><Input required autoComplete="one-time-code" value={code} onChange={(e) => setCode(e.target.value)} /></Field></> : null}</form></Modal>;
}
