# Generated by Django 5.2.17 on 2026-08-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0011_organization_members_slots_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_source', models.CharField(choices=[('none', 'None'), ('stripe', 'Stripe'), ('apple', 'Apple')], db_index=True, default='none', max_length=20)),
                ('external_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('none', 'No paid subscription'), ('trialing', 'Trial'), ('active', 'Active paid'), ('past_due', 'Payment problem / grace'), ('canceled', 'Ended / canceled paid access')], db_index=True, default='none', max_length=20)),
                ('billing_interval', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('subscribed_plan', models.CharField(blank=True, choices=[('plus', 'Plus'), ('business', 'Business')], default='', help_text='Commercial paid/trial tier (plus/business). Blank when none.', max_length=20)),
                ('currency', models.CharField(default='usd', help_text='V1 catalog currency is USD. Stored lowercase ISO-like code.', max_length=3)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('pending_plan', models.CharField(blank=True, choices=[('plus', 'Plus'), ('basic', 'Basic')], default='', help_text='Scheduled destination plan. Applied only at effective_at.', max_length=20)),
                ('pending_change_effective_at', models.DateTimeField(blank=True, null=True)),
                ('payment_failure_started_at', models.DateTimeField(blank=True, null=True)),
                ('payment_grace_deadline', models.DateTimeField(blank=True, null=True)),
                ('last_payment_warning_at', models.DateTimeField(blank=True, null=True)),
                ('payment_warning_count', models.PositiveSmallIntegerField(default=0)),
                ('payment_recovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Workspace subscription',
                'verbose_name_plural': 'Workspace subscriptions',
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='billing_wor_status_7bab92_idx'), models.Index(fields=['status', 'trial_ends_at'], name='billing_wor_status_a98570_idx'), models.Index(fields=['status', 'payment_grace_deadline'], name='billing_wor_status_bdfaa6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_source__in', ['none', 'stripe', 'apple'])), name='billing_workspacesubscription_source_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['none', 'trialing', 'active', 'past_due', 'canceled'])), name='billing_workspacesubscription_status_valid'), models.CheckConstraint(condition=models.Q(('billing_interval__in', ['none', 'monthly', 'yearly'])), name='billing_workspacesubscription_interval_valid'), models.CheckConstraint(condition=models.Q(('subscribed_plan', ''), ('subscribed_plan__in', ['plus', 'business']), _connector='OR'), name='billing_workspacesubscription_plan_valid'), models.CheckConstraint(condition=models.Q(('pending_plan', ''), ('pending_plan__in', ['plus', 'basic']), _connector='OR'), name='billing_workspacesubscription_pending_valid'), models.CheckConstraint(condition=models.Q(models.Q(('trial_ends_at__isnull', True), ('trial_started_at__isnull', True)), models.Q(('trial_ends_at__gt', models.F('trial_started_at')), ('trial_ends_at__isnull', False), ('trial_started_at__isnull', False)), _connector='OR'), name='billing_workspacesubscription_trial_window_valid')],
            },
        ),
    ]
