# Generated by Django 5.2.17 on 2026-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_workspace_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=20)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_summary', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_type'], name='billing_pro_provide_103ce1_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='billing_providerevent_provider_event_unique')],
            },
        ),
    ]
