# Generated by Django 5.2.17 on 2026-09-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_provider_event_processing_and_lookup_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacebuiltintrial',
            new_name='billing_wor_ends_at_33b4bb_idx',
            old_name='billing_wor_ends_at_b8e4a1_idx',
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('plus', 'Plus'), ('business', 'Business'), ('basic', 'Basic')], default='', help_text='Scheduled destination plan. Applied only at effective_at.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='status',
            field=models.CharField(choices=[('none', 'No paid subscription'), ('trialing', 'Provider billing delay'), ('active', 'Active paid'), ('past_due', 'Payment problem / grace'), ('canceled', 'Ended / canceled paid access')], db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='subscribed_plan',
            field=models.CharField(blank=True, choices=[('plus', 'Plus'), ('business', 'Business')], default='', help_text='Commercial paid/deferred-start tier (plus/business). Blank when none.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the provider starts the first paid period. Not the built-in 7-day Business trial.', null=True),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='Provider billing-delay window start (Stripe/Apple). Not the built-in 7-day Business trial.', null=True),
        ),
    ]
