# Generated by Django 5.2.17 on 2026-10-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_checkout_attempt_coupon_market'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacecheckoutattempt',
            new_name='billing_wor_organiz_9c745b_idx',
            old_name='billing_co_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacecheckoutattempt',
            new_name='billing_wor_stripe__d40d85_idx',
            old_name='billing_co_session_idx',
        ),
    ]
