# Generated by Django 5.2.17 on 2026-08-18 06:06

import django.db.models.deletion
import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOnlyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to=groups.models.group_only_participant_photo_upload_to)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('check_in_identifier', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('check_in_enabled', models.BooleanField(default=True)),
                ('check_out_enabled', models.BooleanField(default=False)),
                ('breaks_enabled', models.BooleanField(default=False)),
                ('max_breaks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('automatic_check_in_enabled', models.BooleanField(default=False)),
                ('automatic_check_in_time', models.TimeField(blank=True, null=True)),
                ('require_email', models.BooleanField(default=False)),
                ('require_photo', models.BooleanField(default=False)),
                ('require_check_in_identifier', models.BooleanField(default=False)),
                ('require_pin', models.BooleanField(default=False)),
                ('send_email_after_check_in', models.BooleanField(default=False)),
                ('check_in_email_template', models.TextField(blank=True, default='')),
                ('send_email_after_check_out', models.BooleanField(default=False)),
                ('check_out_email_template', models.TextField(blank=True, default='')),
                ('send_email_after_break', models.BooleanField(default=False)),
                ('break_email_template', models.TextField(blank=True, default='')),
                ('email_sender_mode', models.CharField(choices=[('platform', 'Platform email'), ('custom', 'Custom company sender')], default='platform', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_name', models.CharField(blank=True, default='', max_length=150)),
                ('override_email', models.EmailField(blank=True, default='', max_length=254)),
                ('override_photo', models.ImageField(blank=True, upload_to=groups.models.group_membership_photo_upload_to)),
                ('override_check_in_identifier', models.CharField(blank=True, default='', max_length=80)),
                ('override_pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='groups.group')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
