# Generated by Django 5.2.17 on 2026-08-18 06:06

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='members.member'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='grouponlyparticipant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_only_participants', to='groups.group'),
        ),
        migrations.AddField(
            model_name='grouponlyparticipant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_only_participants', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['organization', 'status'], name='groups_grou_organiz_dfa54c_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='groups_group_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('email_sender_mode__in', ['platform', 'custom'])), name='groups_email_sender_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('breaks_enabled', False), ('max_breaks__gte', 1), _connector='OR'), name='groups_max_breaks_required_when_enabled'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('automatic_check_in_enabled', False), ('automatic_check_in_time__isnull', False), _connector='OR'), name='groups_automatic_check_in_time_required_when_enabled'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('automatic_check_in_enabled', False), ('check_in_enabled', False), _connector='OR'), name='groups_automatic_check_in_only_when_manual_off'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), condition=models.Q(('status', 'active')), name='unique_active_group_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['organization', 'status'], name='groups_grou_organiz_50ab13_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_d0a4fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='unique_member_per_group'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive'])), name='groups_membership_status_valid'),
        ),
        migrations.AddIndex(
            model_name='grouponlyparticipant',
            index=models.Index(fields=['organization', 'status'], name='groups_grou_organiz_c663e8_idx'),
        ),
        migrations.AddIndex(
            model_name='grouponlyparticipant',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_089e62_idx'),
        ),
        migrations.AddConstraint(
            model_name='grouponlyparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='groups_only_participant_status_valid'),
        ),
    ]
