# Generated by Django 5.2.17 on 2026-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kiosk_confirmation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_input_field_1',
            field=models.CharField(blank=True, choices=[('name', 'Name'), ('email', 'Email'), ('identifier', 'Member identifier'), ('pin', 'PIN')], default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_input_field_2',
            field=models.CharField(blank=True, choices=[('name', 'Name'), ('email', 'Email'), ('identifier', 'Member identifier'), ('pin', 'PIN')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_list_show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_list_show_identifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_list_show_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_list_show_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_mode',
            field=models.CharField(choices=[('member_list', 'Member list'), ('input', 'Input mode')], default='member_list', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_return_delay_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_success_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern')], default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='kiosk_welcome_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('kiosk_enabled', False), ('kiosk_mode__in', ['member_list', 'input']), _connector='OR'), name='groups_kiosk_mode_valid'),
        ),
    ]
