# Generated by Django 5.2.17 on 2026-08-21 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_group_product_cleanup'),
        ('groups', '0005_group_participation_slice'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='automatic_check_in_enabled',
            field=models.BooleanField(default=False, help_text='Deprecated. Automatic check-in was removed from the customer product. Column retained for migration compatibility only.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='automatic_check_in_time',
            field=models.TimeField(blank=True, help_text='Deprecated with automatic_check_in_enabled.', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='email_sender_mode',
            field=models.CharField(choices=[('platform', 'Platform email'), ('custom', 'Custom company sender')], default='platform', help_text='Deprecated. Group outgoing email uses GroupEmailSender. Platform Resend remains for account emails only.', max_length=20),
        ),
        migrations.CreateModel(
            name='GroupEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('event_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_summary', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='attendance.actionrecord')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_email_deliveries', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='groups_grou_organiz_08002d_idx'), models.Index(fields=['group', 'created_at'], name='groups_grou_group_i_2a67cb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['sent', 'failed'])), name='groups_email_delivery_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='GroupEmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('custom_smtp', 'Custom SMTP')], default='custom_smtp', max_length=40)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_security', models.CharField(blank=True, choices=[('starttls', 'TLS / STARTTLS'), ('ssl', 'SSL'), ('none', 'None')], default='', max_length=20)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=150)),
                ('provider_settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('needs_verification', 'Needs verification'), ('ready', 'Ready'), ('error', 'Error')], default='not_configured', max_length=30)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_sender', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_email_senders', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='groups_grou_organiz_b4864b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('provider__in', ['custom_smtp'])), name='groups_email_sender_provider_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['not_configured', 'needs_verification', 'ready', 'error'])), name='groups_email_sender_status_valid'), models.CheckConstraint(condition=models.Q(('smtp_security', ''), ('smtp_security__in', ['starttls', 'ssl', 'none']), _connector='OR'), name='groups_email_sender_smtp_security_valid')],
            },
        ),
    ]
