# Generated by Django 5.2.17 on 2026-08-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_email_sender'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupemailsender',
            name='groups_email_sender_smtp_security_valid',
        ),
        migrations.AlterField(
            model_name='groupemailsender',
            name='smtp_security',
            field=models.CharField(blank=True, choices=[('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS'), ('none', 'None')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='groupemailsender',
            constraint=models.CheckConstraint(condition=models.Q(('smtp_security', ''), ('smtp_security__in', ['ssl', 'starttls', 'none']), _connector='OR'), name='groups_email_sender_smtp_security_valid'),
        ),
    ]
