# Generated by Django 5.2.17 on 2026-08-23 01:07

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_yahoo_email_sender_provider'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('structured', 'Structured')], default='standard', help_text='standard: participants belong directly to the Group. structured: participants belong to Classes (GroupSection) inside the Group. Immutable after creation.', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='require_class_pin',
            field=models.BooleanField(default=False, help_text='Structured Groups only. When enabled, Classes require a PIN for future kiosk class entry. Stored now; kiosk behavior deferred.'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('group_type__in', ['standard', 'structured'])), name='groups_group_type_valid'),
        ),
        migrations.AddField(
            model_name='groupsection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupsection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_sections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Required for Structured Groups (Class). Must be null for Standard Groups.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='groups.groupsection'),
        ),
        migrations.AddField(
            model_name='grouponlyparticipant',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Required for Structured Groups (Class). Must be null for Standard Groups.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_only_participants', to='groups.groupsection'),
        ),
        migrations.AddIndex(
            model_name='groupsection',
            index=models.Index(fields=['organization', 'status'], name='groups_grou_organiz_d3222d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsection',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_3f9c7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupsection',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='groups_section_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='groupsection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('group'), condition=models.Q(('status', 'active')), name='unique_active_section_name_per_group'),
        ),
    ]
