# Generated by Django 5.2.17 on 2026-08-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_structured_group_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsection',
            name='class_pin',
            field=models.CharField(blank=True, default='', help_text='Low-security Class PIN for Structured kiosk Class entry when the parent Group has require_class_pin enabled. Not a password.', max_length=12),
        ),
    ]
