# Generated by Django 5.2.17 on 2026-08-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_backfill_group_type_snapshot'),
        ('groups', '0012_class_pin'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='forward_emails',
            field=models.JSONField(blank=True, default=list, help_text='Optional Group-level forwarding recipients (max 3). After-action emails also send private copies to these addresses. Not part of GroupEmailSender credentials.'),
        ),
        migrations.AddField(
            model_name='groupemaildelivery',
            name='recipient_kind',
            field=models.CharField(choices=[('participant', 'Participant'), ('forward', 'Forward'), ('test', 'Test')], default='participant', help_text='Whether this delivery targeted the participant participation email, a Group forward-email copy, or a sender test.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='groupemaildelivery',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_kind__in', ['participant', 'forward', 'test'])), name='groups_email_delivery_recipient_kind_valid'),
        ),
    ]
