# Generated by Django 5.2 for participation emails (up to 3).

from django.db import migrations, models


def backfill_participation_emails(apps, schema_editor):
    GroupMembership = apps.get_model("groups", "GroupMembership")
    GroupOnlyParticipant = apps.get_model("groups", "GroupOnlyParticipant")

    for membership in GroupMembership.objects.all().iterator():
        legacy = (membership.participation_email or "").strip().lower()
        current = membership.participation_emails or []
        if current:
            continue
        membership.participation_emails = [legacy] if legacy else []
        membership.save(update_fields=["participation_emails"])

    for visitor in GroupOnlyParticipant.objects.all().iterator():
        legacy = (visitor.email or "").strip().lower()
        current = visitor.participation_emails or []
        if current:
            continue
        visitor.participation_emails = [legacy] if legacy else []
        visitor.save(update_fields=["participation_emails"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0013_group_forward_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="participation_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Up to 3 Group participation notification emails. "
                    "Independent of Member profile email."
                ),
            ),
        ),
        migrations.AddField(
            model_name="grouponlyparticipant",
            name="participation_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Up to 3 Group participation notification emails for this visitor."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="participation_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text=(
                    "Deprecated scalar mirror of participation_emails[0]. "
                    "Prefer participation_emails."
                ),
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="grouponlyparticipant",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text=(
                    "Deprecated scalar mirror of participation_emails[0]. "
                    "Prefer participation_emails."
                ),
                max_length=254,
            ),
        ),
        migrations.RunPython(backfill_participation_emails, noop_reverse),
    ]
