# Generated by Django 5.2.17 on 2026-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_participation_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='plan_unlocked',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
