# Generated by Django 5.2.17 on 2026-09-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_backfill_group_type_snapshot'),
        ('groups', '0016_hash_operational_pins'),
        ('organizations', '0015_organization_billing_market_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEmailOutboxJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('participant_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('timezone_name', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_outbox_jobs', to='attendance.actionrecord')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_outbox_jobs', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_email_outbox_jobs', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='groups_grou_status_e2e73e_idx'), models.Index(fields=['organization', 'created_at'], name='groups_grou_organiz_31ad75_idx')],
                'constraints': [models.UniqueConstraint(fields=('action_record', 'event_type'), name='groups_email_outbox_action_event_uniq'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'succeeded', 'failed'])), name='groups_email_outbox_status_valid')],
            },
        ),
    ]
