# Generated by Django 5.2.17 on 2026-10-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_saved_email_sender'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedemailsender',
            new_name='groups_save_organiz_bb0265_idx',
            old_name='saved_sender_org_name_idx',
        ),
    ]
