# Generated by Django 5.2.17 on 2026-08-18 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='organizatio_status_54bdfc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='organizations_organization_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='organizatio_organiz_687988_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='one_membership_per_user_per_organization'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_membership_per_user'), models.UniqueConstraint(condition=models.Q(('role', 'owner'), ('status', 'active')), fields=('organization',), name='one_active_owner_per_organization'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'admin', 'staff'])), name='organizations_membership_role_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive'])), name='organizations_membership_status_valid')],
            },
        ),
    ]
