# Generated by Django 5.2.17 on 2026-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_owner_and_workspace_staff_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacestaffaccount',
            new_name='organizatio_organiz_3fc582_idx',
            old_name='organizatio_organiz_8a1d2e_idx',
        ),
    ]
