# Generated by Django 5.2.17 on 2026-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_staff_account_status_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacestaffaccount',
            name='unique_staff_username_per_organization',
        ),
        migrations.AlterField(
            model_name='workspacestaffaccount',
            name='username',
            field=models.CharField(help_text='Globally unique login username. The workspace is resolved from this account.', max_length=150, unique=True),
        ),
    ]
