# Generated by Django - staff group access

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_participation_emails"),
        ("organizations", "0007_staff_admin_requires_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceStaffGroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_access",
                        to="groups.group",
                    ),
                ),
                (
                    "staff_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_access",
                        to="organizations.workspacestaffaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["staff_account_id", "group_id"],
                "indexes": [
                    models.Index(
                        fields=["staff_account"],
                        name="organizatio_staff_a_6e1b0d_idx",
                    ),
                    models.Index(
                        fields=["group"],
                        name="organizatio_group_i_8f4a2c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff_account", "group"),
                        name="unique_staff_group_access",
                    ),
                ],
            },
        ),
    ]
