# Generated by Django 5.2.17 on 2026-08-25 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_workspacestaffgroupaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workspacestaffgroupaccess',
            new_name='organizatio_staff_a_9aead1_idx',
            old_name='organizatio_staff_a_6e1b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacestaffgroupaccess',
            new_name='organizatio_group_i_b13189_idx',
            old_name='organizatio_group_i_8f4a2c_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('plus', 'Plus'), ('business', 'Business')], db_index=True, default='basic', help_text='Internal V1 entitlement plan (basic / plus / business). Defaults to Basic until billing updates this field. Not customer-mutable via workspace APIs.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('plan__in', ['basic', 'plus', 'business'])), name='organizations_organization_plan_valid'),
        ),
    ]
