# Generated by Django 5.2.17 on 2026-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active_standard_groups_slots_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_groups_slots_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='workspace_admins_slots_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='workspace_staff_slots_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacestaffaccount',
            name='plan_unlocked',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
