# Generated by Django 5.2.17 on 2026-08-27 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_members_slots_resolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='organizations_organization_status_valid',
        ),
        migrations.AddField(
            model_name='organization',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_checkstation_account',
            field=models.BooleanField(db_index=True, default=False, help_text='CheckStation-managed/internal workspace. Not a paid subscription. When on, Organization.plan is admin-controlled and customer Subscription/Billing are hidden.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'blocked', 'archived'])), name='organizations_organization_status_valid'),
        ),
    ]
