# Generated by Django 5.2.17 on 2026-10-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organization_billing_market_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_market_override',
            field=models.CharField(choices=[('auto', 'Auto'), ('global', 'Global'), ('jp', 'Japan')], db_index=True, default='auto', help_text='Platform-admin billing market override. Auto resolves to Global for legacy workspaces and never follows request geo. New registrations lock to global or jp at signup. Customers cannot change this field.', max_length=10),
        ),
    ]
