import type { ApiClient, TransportApiClient } from "@checkstation/api";
export type HelpApi = ApiClient | TransportApiClient;
export type DocumentSummary = { id: string; slug: string; language: string; title: string; document_type: string; nav_group: string; nav_group_label: string; description: string; version: string; updated_at: string | null; effective_on: string | null; fallback: boolean };
export type Document = DocumentSummary & { body_markdown: string; canonical_url: string | null };
export type Faq = { id: string; slug: string; question: string; answer_markdown: string; category: string; category_label: string; related_document_slug: string | null; updated_at: string | null };
export type FaqResponse = { categories: Array<{ id: string; label: string }>; entries: Faq[] };
export type StatusSnapshot = { current: { overall: { state: string; label: string }; generated_at: string; last_checked_at: string | null; components: Array<{ id: string; name: string; state: string; label: string; layer: string; description: string }> }; incidents: { active: Array<{ id: string; title: string; summary: string; status_label: string }> }; maintenance: { windows: Array<{ id: string; title: string; starts_at: string; ends_at: string; note: string; active: boolean; upcoming: boolean }> } };
export function getDocuments(api: HelpApi, locale: string) { return api.get<{ documents: DocumentSummary[] }>(`/content/documents/?lang=${encodeURIComponent(locale)}`, { credentials: false }); }
export function getDocument(api: HelpApi, slug: string, locale: string) { return api.get<Document>(`/content/documents/${encodeURIComponent(slug)}/?lang=${encodeURIComponent(locale)}`, { credentials: false }); }
export function getFaq(api: HelpApi, locale: string, category = "", query = "") { const p = new URLSearchParams({ lang: locale }); if (category) p.set("category", category); if (query.trim()) p.set("q", query.trim()); return api.get<FaqResponse>(`/content/faq/?${p}`, { credentials: false }); }
async function statusJson<T>(base: string, path: string, locale: string) { const response = await fetch(`${base.replace(/\/$/, "")}/api/status/${path}/?lang=${locale}`, { cache: "no-store" }); if (!response.ok) throw new Error(`Status request failed (${response.status})`); return response.json() as Promise<T>; }
export async function getStatus(base: string, locale: string): Promise<StatusSnapshot> { const [current, incidents, maintenance] = await Promise.all([statusJson<StatusSnapshot["current"]>(base, "current", locale), statusJson<StatusSnapshot["incidents"]>(base, "incidents", locale).catch(() => ({ active: [] })), statusJson<StatusSnapshot["maintenance"]>(base, "maintenance", locale).catch(() => ({ windows: [] }))]); return { current, incidents, maintenance }; }
