import assert from "node:assert/strict";
import test from "node:test";
import { buildKioskSettingsSavePayload, isKioskSettingsDirty, kioskSettingsFormFromApi, visibleConfirmationMessageFields } from "./kioskSettingsForm";
const api = { mode: "card", card_show_name: true, card_show_participant_code: true, card_show_email: true, use_pin: true, input_field_count: 2, input_second_field: "pin", confirmation_template: "kids", confirmation_check_in_message: "Welcome {name}", confirmation_return_seconds: 3, confirmation_sound_enabled: true, confirmation_vibration_enabled: false, attendance_reset_mode: "daily", attendance_reset_daily_time: "12:00:00", attendance_reset_rolling_hours: 8, attendance_reset_rolling_minutes: 0, exit_code_configured: true, group_require_email: true, group_require_pin: true };
test("normalizes the browser kiosk settings contract", () => { const form = kioskSettingsFormFromApi(api); assert.equal(form.attendance_reset_daily_time, "12:00"); assert.equal(form.confirmation_check_in_message, "Welcome {name}"); assert.equal("confirmation_template" in form, false); });
test("repairs settings that group capabilities do not allow", () => { const form = kioskSettingsFormFromApi({ ...api, group_require_email: false, group_require_pin: false }); assert.equal(form.card_show_email, false); assert.equal(form.use_pin, false); assert.equal(form.input_field_count, 1); assert.equal(form.input_second_field, "name"); });
test("does not send legacy template or unchanged exit code", () => { const form = kioskSettingsFormFromApi(api); const payload = buildKioskSettingsSavePayload(form, { changingExitCode: false, exitCodeConfigured: true }); assert.equal("confirmation_template" in payload, false); assert.equal("exit_code" in payload, false); assert.equal(payload.attendance_reset_daily_time, "12:00:00"); });
test("dirty comparison follows exit-code editing state", () => { const saved = kioskSettingsFormFromApi(api); const changed = { ...saved, exit_code: "ABCD", exit_code_confirm: "ABCD" }; assert.equal(isKioskSettingsDirty(changed, saved, { changingExitCode: false, savedChangingExitCode: false, exitCodeConfigured: true }), false); assert.equal(isKioskSettingsDirty(changed, saved, { changingExitCode: true, savedChangingExitCode: false, exitCodeConfigured: true }), true); });
test("message fields follow enabled actions", () => { assert.deepEqual(visibleConfirmationMessageFields({ check_in_enabled: true, breaks_enabled: true }).map((item) => item.action), ["check_in", "break_start", "break_end"]); });
