export type KioskActionFlags = { check_in_enabled?: boolean; check_out_enabled?: boolean; breaks_enabled?: boolean };
export type KioskSettingsApi = {
  group_id?: number; group_name?: string; mode?: string; card_show_name?: boolean; card_show_participant_code?: boolean; card_show_email?: boolean; use_pin?: boolean; input_field_count?: number; input_second_field?: string; confirmation_template?: string; confirmation_check_in_message?: string; confirmation_check_out_message?: string; confirmation_break_start_message?: string; confirmation_break_end_message?: string; confirmation_return_seconds?: number; confirmation_sound_enabled?: boolean; confirmation_vibration_enabled?: boolean; attendance_reset_mode?: string; attendance_reset_daily_time?: string; attendance_reset_rolling_hours?: number; attendance_reset_rolling_minutes?: number; exit_code_configured?: boolean; group_require_email?: boolean; group_require_pin?: boolean; group_actions?: KioskActionFlags; confirmation_defaults?: Record<string, string>;
};
export type KioskSettingsForm = {
  mode: "card" | "input"; card_show_name: boolean; card_show_participant_code: boolean; card_show_email: boolean; use_pin: boolean; input_field_count: number; input_second_field: string; exit_code: string; exit_code_confirm: string; confirmation_check_in_message: string; confirmation_check_out_message: string; confirmation_break_start_message: string; confirmation_break_end_message: string; confirmation_return_seconds: number; confirmation_sound_enabled: boolean; confirmation_vibration_enabled: boolean; attendance_reset_mode: "daily" | "rolling"; attendance_reset_daily_time: string; attendance_reset_rolling_hours: number; attendance_reset_rolling_minutes: number;
};

export const CONFIRMATION_RETURN_OPTIONS = [1, 3, 5] as const;
export const CONFIRMATION_MESSAGE_FIELDS = [
  { action: "check_in", field: "confirmation_check_in_message", labelKey: "kiosk.messageCheckIn", groupFlag: "check_in_enabled" },
  { action: "check_out", field: "confirmation_check_out_message", labelKey: "kiosk.messageCheckOut", groupFlag: "check_out_enabled" },
  { action: "break_start", field: "confirmation_break_start_message", labelKey: "kiosk.messageBreakStart", groupFlag: "breaks_enabled" },
  { action: "break_end", field: "confirmation_break_end_message", labelKey: "kiosk.messageBreakEnd", groupFlag: "breaks_enabled" },
] as const;
export function visibleConfirmationMessageFields(actions: KioskActionFlags = {}) { return CONFIRMATION_MESSAGE_FIELDS.filter((item) => Boolean(actions[item.groupFlag])); }
function parseApiTime(value?: string) { return value && typeof value === "string" ? value.slice(0, 5) : "00:00"; }

export function kioskSettingsFormFromApi(settings: KioskSettingsApi): KioskSettingsForm {
  const groupRequireEmail = Boolean(settings.group_require_email); const groupRequirePin = Boolean(settings.group_require_pin);
  let inputFieldCount = settings.input_field_count || 1; let inputSecondField = settings.input_second_field || "name"; let usePin = Boolean(settings.use_pin); let cardShowEmail = Boolean(settings.card_show_email);
  if (!groupRequirePin) { usePin = false; if (inputFieldCount === 2 && inputSecondField === "pin") { inputFieldCount = 1; inputSecondField = "name"; } }
  if (!groupRequireEmail) { cardShowEmail = false; if (inputFieldCount === 2 && inputSecondField === "email") { inputFieldCount = 1; inputSecondField = "name"; } }
  return {
    mode: settings.mode === "input" ? "input" : "card", card_show_name: settings.card_show_name !== false, card_show_participant_code: settings.card_show_participant_code !== false, card_show_email: cardShowEmail, use_pin: usePin, input_field_count: inputFieldCount, input_second_field: inputSecondField, exit_code: "", exit_code_confirm: "", confirmation_check_in_message: settings.confirmation_check_in_message || "", confirmation_check_out_message: settings.confirmation_check_out_message || "", confirmation_break_start_message: settings.confirmation_break_start_message || "", confirmation_break_end_message: settings.confirmation_break_end_message || "", confirmation_return_seconds: Number(settings.confirmation_return_seconds) || 3, confirmation_sound_enabled: settings.confirmation_sound_enabled !== false, confirmation_vibration_enabled: Boolean(settings.confirmation_vibration_enabled), attendance_reset_mode: settings.attendance_reset_mode === "rolling" ? "rolling" : "daily", attendance_reset_daily_time: parseApiTime(settings.attendance_reset_daily_time), attendance_reset_rolling_hours: Number(settings.attendance_reset_rolling_hours) || 8, attendance_reset_rolling_minutes: Number(settings.attendance_reset_rolling_minutes) || 0,
  };
}
function comparable(form: KioskSettingsForm, changingExitCode: boolean, exitCodeConfigured: boolean) {
  const count = Number(form.input_field_count) || 1; const exitEditing = changingExitCode || !exitCodeConfigured;
  return { mode: form.mode, card_show_name: form.card_show_name, card_show_participant_code: form.card_show_participant_code, card_show_email: form.card_show_email, use_pin: form.use_pin, input_field_count: count, input_second_field: count === 2 ? form.input_second_field || "name" : "", exit_code: exitEditing ? form.exit_code.trim() : "", exit_code_confirm: exitEditing ? form.exit_code_confirm.trim() : "", confirmation_check_in_message: form.confirmation_check_in_message.trim(), confirmation_check_out_message: form.confirmation_check_out_message.trim(), confirmation_break_start_message: form.confirmation_break_start_message.trim(), confirmation_break_end_message: form.confirmation_break_end_message.trim(), confirmation_return_seconds: Number(form.confirmation_return_seconds) || 3, confirmation_sound_enabled: form.confirmation_sound_enabled, confirmation_vibration_enabled: form.confirmation_vibration_enabled, attendance_reset_mode: form.attendance_reset_mode, attendance_reset_daily_time: form.attendance_reset_daily_time || "00:00", attendance_reset_rolling_hours: Number(form.attendance_reset_rolling_hours) || 0, attendance_reset_rolling_minutes: Number(form.attendance_reset_rolling_minutes) || 0 };
}
export function isKioskSettingsDirty(form: KioskSettingsForm, saved: KioskSettingsForm, options: { changingExitCode: boolean; savedChangingExitCode: boolean; exitCodeConfigured: boolean }) { return JSON.stringify(comparable(form, options.changingExitCode, options.exitCodeConfigured)) !== JSON.stringify(comparable(saved, options.savedChangingExitCode, options.exitCodeConfigured)); }
export function buildKioskSettingsSavePayload(form: KioskSettingsForm, options: { changingExitCode: boolean; exitCodeConfigured: boolean }) {
  const payload: Record<string, string | number | boolean> = { mode: form.mode, card_show_name: form.card_show_name, card_show_participant_code: form.card_show_participant_code, card_show_email: form.card_show_email, use_pin: form.use_pin, input_field_count: form.input_field_count, input_second_field: form.input_field_count === 2 ? form.input_second_field : "", confirmation_check_in_message: form.confirmation_check_in_message, confirmation_check_out_message: form.confirmation_check_out_message, confirmation_break_start_message: form.confirmation_break_start_message, confirmation_break_end_message: form.confirmation_break_end_message, confirmation_return_seconds: Number(form.confirmation_return_seconds) || 3, confirmation_sound_enabled: form.confirmation_sound_enabled, confirmation_vibration_enabled: form.confirmation_vibration_enabled, attendance_reset_mode: form.attendance_reset_mode, attendance_reset_daily_time: `${parseApiTime(form.attendance_reset_daily_time)}:00`, attendance_reset_rolling_hours: Number(form.attendance_reset_rolling_hours) || 0, attendance_reset_rolling_minutes: Number(form.attendance_reset_rolling_minutes) || 0 };
  if (options.changingExitCode || !options.exitCodeConfigured) { payload.exit_code = form.exit_code; payload.exit_code_confirm = form.exit_code_confirm; }
  return payload;
}
