# Generated by Django 5.2.17 on 2026-08-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable public identifier, for example privacy-policy.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('documentation', 'Documentation'), ('legal', 'Legal'), ('help', 'Help')], default='documentation', max_length=32)),
                ('nav_group', models.CharField(choices=[('home', 'Documentation'), ('getting_started', 'Getting Started'), ('using', 'Using CheckStation'), ('legal', 'Legal'), ('help', 'Help')], default='home', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Short public summary used in indexes and meta description.', max_length=300)),
                ('body_markdown', models.TextField(help_text='Canonical Markdown body. Do not store raw HTML as the source.')),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('is_public', models.BooleanField(default=True, help_text='If off, the document is never returned by the public API.')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('effective_on', models.DateField(blank=True, help_text='Public effective date for legal documents.', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal review notes. Never exposed by the public API.')),
            ],
            options={
                'ordering': ('nav_group', 'sort_order', 'title'),
            },
        ),
    ]
