# Generated by Django 5.2.17 on 2026-08-31 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_seed_support'),
        ('organizations', '0013_workspace_tutorial_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('maintenance', 'Maintenance'), ('important', 'Important')], db_index=True, default='info', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('audience', models.CharField(choices=[('all', 'All Workspaces'), ('plan', 'Effective Plan'), ('workspaces', 'Specific Workspaces')], db_index=True, default='all', max_length=16)),
                ('target_plans', models.JSONField(blank=True, default=list, help_text='Effective plan keys when audience is plan: basic, plus, and/or business.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. After this time the announcement is no longer eligible.', null=True)),
                ('include_status_link', models.BooleanField(default=False, help_text='When enabled, Workspace clients may show a View Status action.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal review notes. Never exposed by the Workspace API.')),
                ('target_workspaces', models.ManyToManyField(blank=True, help_text='Target Organizations when audience is specific workspaces.', related_name='platform_announcements', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='content.announcement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('workspace_staff_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgements', to='organizations.workspacestaffaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'announcement'], name='content_ann_user_id_5f5ec3_idx'), models.Index(fields=['workspace_staff_account', 'announcement'], name='content_ann_workspa_dd913f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('workspace_staff_account__isnull', True)), models.Q(('user__isnull', True), ('workspace_staff_account__isnull', False)), _connector='OR'), name='announcement_ack_actor_xor'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('announcement', 'user'), name='announcement_ack_unique_user'), models.UniqueConstraint(condition=models.Q(('workspace_staff_account__isnull', False)), fields=('announcement', 'workspace_staff_account'), name='announcement_ack_unique_staff')],
            },
        ),
    ]
