# Generated by Django 5.2.17 on 2026-09-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_announcement_market_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional. After this time the announcement is no longer eligible. Announcement Admin enters/displays this in Asia/Tokyo; stored timezone-aware.', null=True),
        ),
    ]
