# Generated by Django 5.2.17 on 2026-09-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial_contact_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactrequest',
            new_name='contact_con_categor_2ebcb2_idx',
            old_name='contact_con_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='contactrequest',
            new_name='contact_con_email_4b36f7_idx',
            old_name='contact_con_email_idx',
        ),
    ]
