export {
  CARD_TEMPLATE_IDS,
  DEFAULT_KIOSK_DESIGN,
  INPUT_TEMPLATE_IDS,
  inputTemplateAccent,
  kioskOverlayColor,
  normalizeKioskDesignConfig as normalizeKioskVisualDesign,
  normalizeKioskDesignDocument,
  patchKioskDesignConfig,
  patchMainWithCardTemplate,
  patchMainWithInputTemplate,
  resolveKioskCardTemplate,
  type KioskBackground,
  type KioskDesignConfig as KioskVisualDesign,
  type KioskDesignDocument,
} from "@checkstation/domain";
