import { useRef, useState } from "react";
import { Redirect, router } from "expo-router";
import { Keyboard, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { ApiError, endpoints, fieldErrorsFromBody } from "@checkstation/api";
import { canManageWorkspace } from "@checkstation/domain";
import { Alert, Button, Field, Screen } from "../../../src/components/ui";
import { PageHeader, SectionCard } from "../../../src/components/mobile";
import { PhotoField, appendPhoto, type PhotoSelection } from "../../../src/components/PhotoField";
import { useApp } from "../../../src/lib/AppProvider";
import { space } from "../../../src/theme/tokens";

type MemberResult = { id: number };
export default function NewMemberScreen() {
  const [photo, setPhoto] = useState<PhotoSelection | null>(null);
  const { api, authState, t } = useApp(); const [values, setValues] = useState({ name: "", email: "", phone: "", address: "", notes: "", date_of_birth: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const emailRef = useRef<TextInput | null>(null); const phoneRef = useRef<TextInput | null>(null); const addressRef = useRef<TextInput | null>(null); const notesRef = useRef<TextInput | null>(null);
  if (!canManageWorkspace(authState.session)) return <Redirect href="/(app)/(tabs)/people" />;
  const set = (key: keyof typeof values, value: string) => { setValues((current) => ({ ...current, [key]: value })); setFieldErrors((current) => ({ ...current, [key]: "" })); setError(""); };
  async function submit() { setBusy(true); setError(""); setFieldErrors({}); try { const form = new FormData(); Object.entries(values).forEach(([key, value]) => form.append(key, value.trim())); if (photo) appendPhoto(form, photo); const member = await api.request<MemberResult>(endpoints.members(), { method: "POST", formData: form }); Keyboard.dismiss(); router.replace(`/(app)/member/${member.id}`); } catch (caught) { if (caught instanceof ApiError) { const fields = fieldErrorsFromBody(caught.data); setFieldErrors(fields); if (!Object.values(fields).some(Boolean)) setError(caught.message); } else setError(t("common.error")); } finally { setBusy(false); } }
  return <Screen style={styles.screen}><ScrollView contentContainerStyle={styles.content} keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled"><PageHeader title={t("members.add")} description={t("members.addDescription")} /><SectionCard><View style={styles.form}><Field autoFocus error={fieldErrors.name} label={t("members.name")} onChangeText={(value) => set("name", value)} onSubmitEditing={() => emailRef.current?.focus()} returnKeyType="next" value={values.name} /><Field ref={emailRef} autoCapitalize="none" autoComplete="email" error={fieldErrors.email} keyboardType="email-address" label={t("auth.email")} onChangeText={(value) => set("email", value)} onSubmitEditing={() => phoneRef.current?.focus()} returnKeyType="next" textContentType="emailAddress" value={values.email} /><Field ref={phoneRef} autoComplete="tel" error={fieldErrors.phone} keyboardType="phone-pad" label={t("members.phone")} onChangeText={(value) => set("phone", value)} onSubmitEditing={() => addressRef.current?.focus()} returnKeyType="next" textContentType="telephoneNumber" value={values.phone} /><Field ref={addressRef} autoComplete="street-address" error={fieldErrors.address} label={t("members.address")} onChangeText={(value) => set("address", value)} onSubmitEditing={() => notesRef.current?.focus()} returnKeyType="next" textContentType="fullStreetAddress" value={values.address} /><Field ref={notesRef} blurOnSubmit error={fieldErrors.notes} label={t("members.notes")} multiline numberOfLines={4} onChangeText={(value) => set("notes", value)} returnKeyType="done" textAlignVertical="top" value={values.notes} /><Field label={t("members.birthday")} hint={t("members.dateHint")} value={values.date_of_birth} onChangeText={(value) => set("date_of_birth", value)} error={fieldErrors.date_of_birth} /><PhotoField value={photo} onChange={setPhoto} /><Alert message={error} /><Button disabled={busy} label={busy ? t("members.saving") : t("members.save")} loading={busy} onPress={() => void submit()} /></View></SectionCard></ScrollView></Screen>;
}
const styles = StyleSheet.create({ screen: { padding: 0 }, content: { padding: space.lg, paddingBottom: space.xxxl, gap: space.lg, width: "100%", maxWidth: 720, alignSelf: "center" }, form: { gap: space.lg } });
