# Generated by Django 5.2.17 on 2026-08-18 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('members', '0001_initial'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_kind', models.CharField(choices=[('member', 'Member'), ('group_only_participant', 'Group-only participant')], max_length=30)),
                ('action_type', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('break_start', 'Break start'), ('break_end', 'Break end')], max_length=30)),
                ('source', models.CharField(choices=[('kiosk', 'Kiosk'), ('automatic', 'Automatic / preset'), ('owner', 'Owner / manual')], default='kiosk', max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant_name_snapshot', models.CharField(max_length=150)),
                ('participant_email_snapshot', models.EmailField(blank=True, default='', max_length=254)),
                ('participant_check_in_identifier_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('kiosk_note_snapshot', models.CharField(blank=True, default='', max_length=250)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_records', to='groups.group')),
                ('group_only_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_records', to='groups.grouponlyparticipant')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_records', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'group', 'performed_at'], name='attendance__organiz_233b53_idx'), models.Index(fields=['group', 'participant_kind', 'performed_at'], name='attendance__group_i_f92d97_idx')],
            },
        ),
    ]
