# Generated by Django 5.2.17 on 2026-08-19 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0002_member_profile_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Live Member link. SET_NULL when a Member is permanently deleted so snapshot fields remain the historical identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_records', to='members.member'),
        ),
    ]
