# Generated by Django 5.2.17 on 2026-08-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_actionrecord_source_group_id'),
        ('groups', '0012_class_pin'),
        ('members', '0002_member_profile_cleanup'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionrecord',
            new_name='attendance__organiz_a11ddc_idx',
            old_name='attendance__organiz_srcgrp_idx',
        ),
        migrations.AddField(
            model_name='actionrecord',
            name='class_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Class display name at action time. Not rewritten on rename, archive, or permanent delete.', max_length=150),
        ),
        migrations.AddField(
            model_name='actionrecord',
            name='group_type_snapshot',
            field=models.CharField(blank=True, default='', help_text='Immutable Group type at record creation (standard/structured). Survives permanent Group deletion so reports know whether Class columns apply.', max_length=20),
        ),
        migrations.AddField(
            model_name='actionrecord',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Live Class link for Structured Group actions. SET_NULL when a Class is permanently deleted so snapshot fields remain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_records', to='groups.groupsection'),
        ),
        migrations.AddField(
            model_name='actionrecord',
            name='source_section_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Immutable Class (GroupSection) primary key at record creation. Survives permanent Class deletion so attendance reports can still group by historical Class identity.', null=True),
        ),
        migrations.AddIndex(
            model_name='actionrecord',
            index=models.Index(fields=['organization', 'source_section_id', 'performed_at'], name='attendance__organiz_ffc51a_idx'),
        ),
    ]
