import { useCallback, useEffect, useState, type FormEvent } from "react";
import { endpoints } from "@checkstation/api";
import { Alert, Badge, Button, Card, DataRow, Empty, Field, Input, Loading, Modal, Segmented, formatError } from "./ui";
import { useApp } from "../lib/AppProvider";
export type DesktopClass = { id:number;name:string;participant_count?:number;status:string;has_class_pin?:boolean };
export function GroupClassesPanel({groupId,canManage,onSelect}:{groupId:string;canManage:boolean;onSelect:(row:DesktopClass)=>void}){
  const{api,t}=useApp(); const[rows,setRows]=useState<DesktopClass[]>([]); const[status,setStatus]=useState<"active"|"archived">("active"); const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[editing,setEditing]=useState<DesktopClass|{id:0;name:"";status:"active"}|null>(null); const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await api.get<DesktopClass[]|{results:DesktopClass[]}>(`${endpoints.groupClasses(groupId)}?status=${status}`);setRows(Array.isArray(data)?data:data.results||[]);}catch(caught){setError(formatError(caught,t("common.error")));}finally{setLoading(false);}},[api,groupId,status,t]); useEffect(()=>{void load();},[load]);
  async function lifecycle(row:DesktopClass,remove=false){const key=remove?"classes.deleteHint":row.status==="archived"?"classes.restore":"classes.archiveHint";if(!confirm(t(key,{name:row.name})))return;setBusy(true);try{if(remove)await api.post(endpoints.groupClassPermanentDelete(groupId,row.id),{});else await api.post(row.status==="archived"?endpoints.groupClassRestore(groupId,row.id):endpoints.groupClassArchive(groupId,row.id),{});await load();}catch(caught){setError(formatError(caught,t("common.error")));}finally{setBusy(false);}}
  return <Card title={t("groups.classes")}><div className="tabs-line"><Segmented value={status} onChange={setStatus} options={[{value:"active",label:t("groups.active")},{value:"archived",label:t("groups.archived")}]}/>{canManage&&status==="active"?<Button onClick={()=>setEditing({id:0,name:"",status:"active"})}>{t("classes.create")}</Button>:null}</div><Alert>{error}</Alert>{loading?<Loading label={t("common.loading")}/>:rows.length?<div className="data-list">{rows.map(row=><DataRow key={row.id} title={row.name} detail={t("groups.participants",{count:row.participant_count||0})} badge={<Badge tone={row.status==="active"?"green":"neutral"}>{row.status==="active"?t("groups.active"):t("groups.archived")}</Badge>} onClick={()=>onSelect(row)} actions={canManage?<><Button className="button-sm" variant="secondary" onClick={()=>setEditing(row)}>{t("classes.edit")}</Button><Button className="button-sm" variant="danger" disabled={busy} onClick={()=>void lifecycle(row)}>{t(row.status==="active"?"classes.archive":"classes.restore")}</Button>{row.status==="archived"?<Button className="button-sm" variant="danger" disabled={busy} onClick={()=>void lifecycle(row,true)}>{t("classes.delete")}</Button>:null}</>:undefined}/>)}</div>:<Empty title={t("classes.empty")}/>} {editing?<ClassEditor groupId={groupId} value={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load();}}/>:null}</Card>;
}
function ClassEditor({groupId,value,onClose,onSaved}:{groupId:string;value:DesktopClass;onClose:()=>void;onSaved:()=>void}){const{api,t}=useApp();const[name,setName]=useState(value.name);const[pin,setPin]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function save(event:FormEvent){event.preventDefault();setBusy(true);try{const payload={name,...(pin?{class_pin:pin}:{})};if(value.id)await api.patch(endpoints.groupClass(groupId,value.id),payload);else await api.post(endpoints.groupClasses(groupId),payload);onSaved();}catch(caught){setError(formatError(caught,t("common.error")));}finally{setBusy(false);}}return <Modal title={t(value.id?"classes.edit":"classes.create")} onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>{t("common.cancel")}</Button><Button form="class-editor" type="submit" loading={busy}>{t("common.save")}</Button></>}><form id="class-editor" className="form" onSubmit={save}><Field label={t("classes.name")}><Input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label={t("kiosk.pin")} hint={t("classes.pinHint")}><Input type="password" value={pin} onChange={e=>setPin(e.target.value)}/></Field><Alert>{error}</Alert></form></Modal>;}
