import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";
import checkStationLogo from "../../../../frontend/src/assets/brand/logo-mark.png";

export function BrandMark({ className = "", decorative = true }: { className?: string; decorative?: boolean }) { return <img className={`brand-logo${className ? ` ${className}` : ""}`} src={checkStationLogo} alt={decorative ? "" : "CheckStation"} width="64" height="64" />; }
export function Brand({ compact = false }: { compact?: boolean }) { return <div className={`brand${compact ? " brand-compact" : ""}`}><BrandMark /><span><strong>CheckStation</strong>{compact ? null : <small>Workspace</small>}</span></div>; }
export function Page({ children, narrow = false }: { children: ReactNode; narrow?: boolean }) { return <div className={`page${narrow ? " page-narrow" : ""}`}>{children}</div>; }
export function PageHeader({ title, description, eyebrow, actions }: { title: string; description?: string; eyebrow?: string; actions?: ReactNode }) { return <header className="page-header"><div>{eyebrow ? <div className="eyebrow">{eyebrow}</div> : null}<h1>{title}</h1>{description ? <p>{description}</p> : null}</div>{actions ? <div className="page-actions">{actions}</div> : null}</header>; }
export function Card({ title, description, children, className = "" }: { title?: string; description?: string; children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{title || description ? <header className="card-header">{title ? <h2>{title}</h2> : null}{description ? <p>{description}</p> : null}</header> : null}<div className="card-body">{children}</div></section>; }
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; loading?: boolean };
export function Button({ variant = "primary", loading, className = "", children, disabled, ...props }: ButtonProps) { return <button className={`button button-${variant} ${className}`} disabled={disabled || loading} {...props}>{loading ? <span className="spinner" /> : null}<span>{children}</span></button>; }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className={`field${error ? " field-error" : ""}`}><span className="field-label">{label}</span>{hint ? <span className="field-hint">{hint}</span> : null}{children}{error ? <span className="field-error-text">{error}</span> : null}</label>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="input" {...props} />; }
export function TextArea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className="input textarea" {...props} />; }
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select className="input select" {...props} />; }
export function Switch({ checked, onChange, label, disabled }: { checked: boolean; onChange: (checked: boolean) => void; label: string; disabled?: boolean }) { return <button aria-label={label} aria-pressed={checked} className={`switch${checked ? " is-on" : ""}`} disabled={disabled} onClick={() => onChange(!checked)} type="button"><span /></button>; }
export function Alert({ children, tone = "error" }: { children?: ReactNode; tone?: "error" | "success" | "info" | "warning" }) { return children ? <div className={`alert alert-${tone}`} role="alert">{children}</div> : null; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "blue" | "green" | "warning" | "danger" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function ActionBadge({ action, label }: { action?: string; label: string }) { const tone = action === "check_in" ? "check-in" : action === "check_out" ? "check-out" : action === "break_start" || action === "break_end" ? "break" : "default"; return <span className={`action-badge action-${tone}`}>{label}</span>; }
export function Segmented<T extends string>({ value, options, onChange, label }: { value: T; options: Array<{ value: T; label: string }>; onChange: (value: T) => void; label?: string }) { return <div aria-label={label} className="segmented" role="tablist">{options.map((option) => <button aria-selected={option.value === value} className={option.value === value ? "is-active" : ""} key={option.value} onClick={() => onChange(option.value)} role="tab" type="button">{option.label}</button>)}</div>; }
export function Loading({ label }: { label: string }) { return <div className="state"><span className="spinner spinner-dark" /><p>{label}</p></div>; }
export function Empty({ title, body, action }: { title: string; body?: string; action?: ReactNode }) { return <div className="state empty-state"><span className="empty-icon">◇</span><h3>{title}</h3>{body ? <p>{body}</p> : null}{action}</div>; }
export function Modal({ title, children, onClose, actions }: { title: string; children: ReactNode; onClose: () => void; actions?: ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section aria-modal="true" className="modal" role="dialog"><header><h2>{title}</h2><button aria-label="Close" className="icon-button" onClick={onClose} type="button">×</button></header><div className="modal-body">{children}</div>{actions ? <footer>{actions}</footer> : null}</section></div>; }
export function DataRow({ title, detail, meta, badge, actions, onClick, avatar }: { title: string; detail?: string; meta?: string; badge?: ReactNode; actions?: ReactNode; onClick?: () => void; avatar?: ReactNode }) { const content = <>{avatar}<div className="row-main"><div className="row-title-line"><strong>{title}</strong>{badge}</div>{detail ? <span>{detail}</span> : null}</div>{meta ? <span className="row-meta">{meta}</span> : null}{actions ? <div className="row-actions" onClick={(event) => event.stopPropagation()}>{actions}</div> : null}{onClick ? <span className="chevron">›</span> : null}</>; return onClick ? <button className="data-row data-row-button" onClick={onClick} type="button">{content}</button> : <div className="data-row">{content}</div>; }
export function Stat({ label, value, hint, tone = "blue", onClick }: { label: string; value: number | string; hint?: string; tone?: "blue" | "cyan" | "green"; onClick?: () => void }) { const Tag = onClick ? "button" : "div"; return <Tag className={`stat stat-${tone}`} onClick={onClick}><span>{label}</span><strong>{value}</strong>{hint ? <small>{hint}</small> : null}</Tag>; }
export function formatError(error: unknown, fallback: string) { return error instanceof Error ? error.message : fallback; }
