# Generated by Django 5.2.17 on 2026-08-18 06:06

import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(editable=False, help_text='Automatically generated immutable internal Member code.', max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to=members.models.member_photo_upload_to)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('check_in_identifier', models.CharField(blank=True, default='', help_text='Optional customer-entered identifier, e.g. STUDENT-123.', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'internal_code'],
                'indexes': [models.Index(fields=['organization', 'status'], name='members_mem_organiz_122411_idx'), models.Index(fields=['organization', 'name'], name='members_mem_organiz_aa9a7b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='members_member_status_valid'), models.CheckConstraint(condition=models.Q(('internal_code__regex', '^MBR-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$')), name='members_internal_code_format')],
            },
        ),
    ]
