# Generated by Django 5.2.17 on 2026-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='members_internal_code_format',
        ),
        migrations.RemoveField(
            model_name='member',
            name='internal_code',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='check_in_identifier',
            field=models.CharField(blank=True, default='', help_text='Deprecated Member-profile field. Kept so Group membership and kiosk identification can still fall back to an existing value until participation identification is redesigned.', max_length=80),
        ),
        migrations.AlterField(
            model_name='member',
            name='pin_hash',
            field=models.CharField(blank=True, default='', help_text='Deprecated Member-profile field. Kept so Group membership and kiosk PIN checks can still use an existing Member PIN until participation PINs are redesigned.', max_length=128),
        ),
    ]
