# Generated by Django 5.2.17 on 2026-08-19 09:49

import django.db.models.deletion
import kiosk_builder.config_schema
import kiosk_builder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_group_kiosk_confirmation_message_group_kiosk_enabled_and_more'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=kiosk_builder.config_schema.default_config)),
                ('header_logo', models.ImageField(blank=True, upload_to=kiosk_builder.models.kiosk_logo_upload_to)),
                ('main_background_image', models.ImageField(blank=True, upload_to=kiosk_builder.models.kiosk_background_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_design', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiosk_designs', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='kiosk_build_organiz_fb149b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('group',), name='unique_kiosk_design_per_group')],
            },
        ),
    ]
