# Generated by Django 5.2.17 on 2026-08-20 02:41

import django.db.models.deletion
from django.db import migrations, models


def backfill_kiosk_settings(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    KioskSettings = apps.get_model("kiosk_builder", "KioskSettings")
    KioskDesign = apps.get_model("kiosk_builder", "KioskDesign")

    for group in Group.objects.all().iterator():
        if KioskSettings.objects.filter(group_id=group.pk).exists():
            continue
        mode = "input"
        if group.kiosk_mode == "member_list":
            mode = "card"
        card_show_name = bool(group.kiosk_list_show_name)
        card_show_code = bool(group.kiosk_list_show_identifier)
        card_show_email = bool(group.kiosk_list_show_email)
        if mode == "card" and not (card_show_name or card_show_code or card_show_email):
            card_show_name = True
            card_show_code = True
        use_pin = False
        input_field_count = 1
        input_second_field = ""
        if mode == "input":
            f2 = group.kiosk_input_field_2 or ""
            if f2:
                input_field_count = 2
                if f2 == "name":
                    input_second_field = "name"
                elif f2 == "email":
                    input_second_field = "email"
                elif f2 == "pin":
                    input_second_field = "pin"
                    use_pin = True
                else:
                    input_second_field = "name"
        footer_enabled = False
        design = KioskDesign.objects.filter(group_id=group.pk).first()
        if design and isinstance(design.config, dict):
            footer_enabled = bool((design.config.get("footer") or {}).get("enabled"))
        KioskSettings.objects.create(
            organization_id=group.organization_id,
            group_id=group.pk,
            mode=mode,
            card_show_name=card_show_name,
            card_show_participant_code=card_show_code or mode == "card",
            card_show_email=card_show_email,
            use_pin=use_pin,
            input_field_count=input_field_count,
            input_second_field=input_second_field,
            header_enabled=True,
            footer_enabled=footer_enabled,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_participation_slice'),
        ('kiosk_builder', '0003_require_group_on_kioskdesign'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('card', 'Card'), ('input', 'Input')], default='card', max_length=20)),
                ('card_show_name', models.BooleanField(default=True)),
                ('card_show_participant_code', models.BooleanField(default=True)),
                ('card_show_email', models.BooleanField(default=False)),
                ('use_pin', models.BooleanField(default=False, help_text='When enabled in Card mode, PIN is required after card selection.')),
                ('input_field_count', models.PositiveSmallIntegerField(default=1)),
                ('input_second_field', models.CharField(blank=True, choices=[('name', 'Name'), ('email', 'Email'), ('pin', 'PIN')], default='', max_length=20)),
                ('header_enabled', models.BooleanField(default=True)),
                ('footer_enabled', models.BooleanField(default=False)),
                ('exit_code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_settings', to='groups.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiosk_settings', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='kiosk_build_organiz_ae0f7a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ['card', 'input'])), name='kiosk_settings_mode_valid'), models.CheckConstraint(condition=models.Q(('input_field_count__in', [1, 2])), name='kiosk_settings_input_field_count_valid')],
            },
        ),
        migrations.RunPython(backfill_kiosk_settings, migrations.RunPython.noop),
    ]
