# Generated by Django 5.2.17 on 2026-08-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_yahoo_email_sender_provider'),
        ('kiosk_builder', '0006_kiosk_confirmation_settings'),
        ('organizations', '0006_workspace_id_and_per_workspace_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosksettings',
            name='attendance_reset_daily_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='kiosksettings',
            name='attendance_reset_mode',
            field=models.CharField(choices=[('daily', 'Daily'), ('rolling', 'Rolling')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='kiosksettings',
            name='attendance_reset_rolling_hours',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='kiosksettings',
            name='attendance_reset_rolling_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kiosksettings',
            name='manual_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='kiosksettings',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_reset_mode__in', ['daily', 'rolling'])), name='kiosk_settings_attendance_reset_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='kiosksettings',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_reset_rolling_minutes__lt', 60)), name='kiosk_settings_attendance_reset_rolling_minutes_valid'),
        ),
    ]
