/** Typed path helpers for CheckStation workspace API (relative to /api). */

export const endpoints = {
  csrf: () => "/auth/csrf/",
  register: () => "/auth/register/",
  forgotPassword: () => "/auth/forgot-password/",
  resetPassword: () => "/auth/reset-password/",
  recoverAccountStart: () => "/auth/recover-account/",
  recoverAccountConfirm: () => "/auth/recover-account/confirm/",
  recoverAccountStatus: () => "/auth/recover-account/status/",
  recoverAccountTwoFactor: () => "/auth/recover-account/2fa/",
  recoverAccountComplete: () => "/auth/recover-account/complete/",
  recoverAccountVerifyPrimary: () => "/auth/recover-account/verify-primary/",
  ownerLogin: () => "/auth/login/",
  staffLogin: () => "/auth/staff-login/",
  logout: () => "/auth/logout/",
  appleNativeComplete: () => "/auth/apple/native/",
  googleNativeComplete: () => "/auth/google/native/",
  ownerTotpChallenge: () => "/auth/owner-2fa/challenge/",
  workspace: () => "/workspace/",
  dashboard: () => "/dashboard/",
  account: () => "/auth/account/",
  accountPrimaryEmail: () => "/auth/account/primary-email/",
  accountPrimaryEmailResend: () => "/auth/account/primary-email/resend/",
  accountPrimaryEmailCancel: () => "/auth/account/primary-email/cancel/",
  accountBackupEmail: () => "/auth/account/backup-email/",
  accountBackupEmailRemove: () => "/auth/account/backup-email/remove/",
  accountBackupEmailResend: () => "/auth/account/backup-email/resend/",
  accountBackupEmailCancel: () => "/auth/account/backup-email/cancel/",
  billing: () => "/billing/",
  billingCatalog: () => "/billing/catalog/",
  billingFuturePlan: () => "/billing/future-plan/",
  billingFuturePlanClear: () => "/billing/future-plan/clear/",
  billingAppleVerify: () => "/billing/apple/verify/",
  members: () => "/members/",
  member: (id: number | string) => `/members/${id}/`,
  groups: () => "/groups/",
  group: (id: number | string) => `/groups/${id}/`,
  groupMemberships: (groupId: number | string) => `/groups/${groupId}/memberships/`,
  groupParticipants: (groupId: number | string) => `/groups/${groupId}/participants/`,
  kiosk: (groupId: number | string) => `/groups/${groupId}/kiosk/`,
  kioskIdentify: (groupId: number | string) => `/groups/${groupId}/kiosk/identify/`,
  kioskPerform: (groupId: number | string) => `/groups/${groupId}/kiosk/perform/`,
  kioskExit: () => "/kiosk/exit/",
  kioskSettings: (groupId: number | string) => `/groups/${groupId}/kiosk-settings/`,
  kioskDesign: (groupId: number | string) => `/groups/${groupId}/kiosk-design/`,
  kioskPresets: () => "/kiosk-presets/",
  groupMembership: (groupId: number | string, membershipId: number | string) => `/groups/${groupId}/memberships/${membershipId}/`,
  groupParticipant: (groupId: number | string, participantId: number | string) => `/groups/${groupId}/participants/${participantId}/`,
  groupAvailableMembers: (groupId: number | string) => `/groups/${groupId}/available-members/`,
  groupArchive: (groupId: number | string) => `/groups/${groupId}/archive/`,
  groupRestore: (groupId: number | string) => `/groups/${groupId}/restore/`,
  groupClasses: (groupId: number | string) => `/groups/${groupId}/classes/`,
  groupClass: (groupId: number | string, sectionId: number | string) => `/groups/${groupId}/classes/${sectionId}/`,
  groupClassArchive: (groupId: number | string, sectionId: number | string) => `/groups/${groupId}/classes/${sectionId}/archive/`,
  groupClassRestore: (groupId: number | string, sectionId: number | string) => `/groups/${groupId}/classes/${sectionId}/restore/`,
  groupClassPermanentDelete: (groupId: number | string, sectionId: number | string) => `/groups/${groupId}/classes/${sectionId}/permanently-delete/`,
  groupEmailSender: (groupId: number | string) => `/groups/${groupId}/email-sender/`,
  groupEmailSenderTest: (groupId: number | string) => `/groups/${groupId}/email-sender/test/`,
  savedEmailSenders: () => "/saved-email-senders/",
  savedEmailSender: (id: number | string) => `/saved-email-senders/${id}/`,
  history: () => "/history/",
  attendanceReportOptions: () => "/history/attendance-report/options/",
  attendanceReport: () => "/history/attendance-report/",
  attendanceReportExport: () => "/history/attendance-report/export/",
  workspaceStaff: () => "/workspace-staff/",
  workspaceStaffAccount: (id: number | string) => `/workspace-staff/${id}/`,
  workspaceStaffPassword: (id: number | string) => `/workspace-staff/${id}/reset-password/`,
  workspaceStaffGroupAccess: (id: number | string) => `/workspace-staff/${id}/group-access/`,
  planLockSelection: (kind: string) => `/plan-locks/selection/?kind=${encodeURIComponent(kind)}`,
  planLockSelectionUpdate: () => "/plan-locks/selection/",
  changePassword: () => "/auth/change-password/",
  setPassword: () => "/auth/set-password/",
  ownerTwoFactorSetup: () => "/auth/owner-2fa/setup/",
  ownerTwoFactorVerify: () => "/auth/owner-2fa/setup/verify/",
  ownerTwoFactorRegenerate: () => "/auth/owner-2fa/recovery-codes/regenerate/",
  ownerTwoFactorDisable: () => "/auth/owner-2fa/disable/",
  announcements: () => "/announcements/",
  contactCategories: () => "/contact/categories/",
  contactSuggestions: (category: string, subcategory: string, lang?: string) => {
    const query = new URLSearchParams({
      category,
      subcategory,
    });
    if (lang) query.set("lang", lang);
    return `/contact/suggestions/?${query.toString()}`;
  },
  contactWorkspace: () => "/contact/workspace/",
} as const;
