/** Typed path helpers for CheckStation workspace API (relative to /api). */

export const endpoints = {
  csrf: () => "/auth/csrf/",
  register: () => "/auth/register/",
  ownerLogin: () => "/auth/login/",
  staffLogin: () => "/auth/staff-login/",
  logout: () => "/auth/logout/",
  ownerTotpChallenge: () => "/auth/owner-2fa/challenge/",
  workspace: () => "/workspace/",
  dashboard: () => "/dashboard/",
  account: () => "/auth/account/",
  billing: () => "/billing/",
  billingCatalog: () => "/billing/catalog/",
  members: () => "/members/",
  member: (id: number | string) => `/members/${id}/`,
  groups: () => "/groups/",
  group: (id: number | string) => `/groups/${id}/`,
  groupMemberships: (groupId: number | string) => `/groups/${groupId}/memberships/`,
  groupParticipants: (groupId: number | string) => `/groups/${groupId}/participants/`,
  groupClasses: (groupId: number | string) => `/groups/${groupId}/classes/`,
  kiosk: (groupId: number | string) => `/groups/${groupId}/kiosk/`,
  kioskIdentify: (groupId: number | string) => `/groups/${groupId}/kiosk/identify/`,
  kioskPerform: (groupId: number | string) => `/groups/${groupId}/kiosk/perform/`,
  kioskExit: () => "/kiosk/exit/",
  kioskSettings: (groupId: number | string) => `/groups/${groupId}/kiosk-settings/`,
  history: () => "/history/",
  attendanceReport: () => "/history/attendance-report/",
  workspaceStaff: () => "/workspace-staff/",
  announcements: () => "/announcements/",
} as const;
