export const managementEn = {
  "common.continue": "Continue", "accountLink.title": "Complete email verification", "accountLink.hint": "Copy the CheckStation link from your email and paste it here to continue inside the app. Automatic opening from email is not configured yet.", "accountLink.link": "Link from your email", "accountLink.open": "Use a link from email", "accountLink.invalid": "Paste a complete CheckStation verification, recovery, or password-reset link.", "accountLink.expired": "This recovery session is no longer available. Request a new recovery link.", "accountLink.newEmailHint": "Check your new login email. Copy its verification link and continue here to complete recovery.", "accountLink.done": "Completed. You can now continue to CheckStation.", "accountLink.continue": "Complete the required verification below.",
  "common.save": "Save", "common.confirm": "Confirm", "kiosk.back": "Back to kiosk", "kiosk.breakStart": "Start break", "kiosk.breakEnd": "End break", "kiosk.code": "Participant code", "kiosk.enterClassPin": "Enter Class PIN", "kiosk.selectClass": "Select a Class", "kiosk.verify": "Verify", "kiosk.recorded": "Action recorded",
  "members.choosePhoto": "Choose photo",
  "classes.create": "Create Class", "classes.edit": "Edit Class", "classes.import": "Copy Standard Group as Class", "classes.source": "Source Group", "classes.name": "Class name", "classes.pinHint": "Leave blank to keep the existing PIN. For new Classes, follow the Group's PIN requirement.", "classes.archive": "Archive Class", "classes.restore": "Restore Class", "classes.delete": "Delete Class permanently", "classes.archiveHint": "Archive {name}? Attendance history is retained.", "classes.deleteHint": "Permanently delete {name}? This cannot be undone.", "classes.back": "Back to Classes", "classes.search": "Search Classes", "classes.empty": "No Classes in this view.",
  "account.changeEmail": "Change login email", "account.setBackup": "Set backup email", "account.removeBackup": "Remove backup email", "account.removeBackupHint": "Removing your backup email removes this account-recovery option.", "account.pendingEmail": "Awaiting verification: {email}", "account.resend": "Resend verification", "account.cancelEmail": "Cancel pending change", "account.verificationSent": "Verification email sent.", "account.emailVerifyHint": "CheckStation will send a verification link to the new address. Your current email stays in use until verification is complete.",
  "manage.discardTitle": "Discard changes?", "manage.discardBody": "Your unsaved changes will be lost.", "manage.discard": "Discard", "manage.saved": "Changes saved.",
  "staff.create": "Create account", "staff.edit": "Edit account", "staff.resetPassword": "Reset password", "staff.groupAccess": "Group access", "staff.accessHint": "Staff can only access the Groups selected here. New Staff accounts have no Group access.",
  "staff.emailHint": "Required for Admin accounts; optional for Staff.", "staff.deactivate": "Deactivate", "staff.activate": "Reactivate", "staff.delete": "Delete permanently", "staff.deleteConfirm": "Permanently delete {name}? This cannot be undone.", "staff.statusConfirm": "Change access for {name}? Deactivated accounts cannot sign in.", "staff.passwordHint": "Set a new password for this account. Existing password strength rules apply.", "staff.search": "Search Staff", "staff.searchGroups": "Search Groups", "staff.accessSaved": "Group access saved.", "staff.saveAccess": "Save access", "staff.role": "Role",
  "security.currentPassword": "Current password", "security.newPassword": "New password", "security.confirmPassword": "Confirm new password", "security.changePassword": "Change password", "security.setup": "Set up two-factor authentication", "security.disable": "Disable two-factor authentication", "security.regenerate": "Regenerate recovery codes", "security.setupKey": "Setup key", "security.setupHint": "Add this key to your authenticator app, then enter its 6-digit code below.", "security.recoveryCodes": "Recovery codes", "security.codesHint": "Save these codes somewhere safe. They are shown only once. Regenerating codes invalidates the previous set.", "security.done": "I have saved my codes", "security.code": "Authenticator code", "security.recoveryCode": "Recovery code", "security.passwordUnavailable": "This account needs provider re-verification for this action. Native Google/Apple verification is not available yet.",
  "members.edit": "Edit Member", "members.save": "Save Member", "members.archive": "Archive Member", "members.restore": "Restore Member", "members.archiveConfirm": "Archive {name}? Their attendance history will be retained.", "members.delete": "Delete permanently", "members.deleteConfirm": "Permanently delete {name}? This cannot be undone.", "members.birthday": "Date of birth", "members.dateHint": "YYYY-MM-DD, or leave blank", "members.removePhoto": "Remove photo",
};
export const managementJa: Record<keyof typeof managementEn, string> = {
  "common.continue": "続ける", "accountLink.title": "メール確認を完了", "accountLink.hint": "メール内のCheckStationリンクをコピーして貼り付けると、アプリ内で続けられます。メールからの自動起動は未設定です。", "accountLink.link": "メール内のリンク", "accountLink.open": "メール内のリンクを使用", "accountLink.invalid": "CheckStationの確認・復旧・パスワード再設定リンクを完全な形で貼り付けてください。", "accountLink.expired": "復旧セッションが終了しました。新しい復旧リンクをリクエストしてください。", "accountLink.newEmailHint": "新しいログインメールを確認し、確認リンクをコピーしてここで復旧を完了してください。", "accountLink.done": "完了しました。CheckStationを続けて利用できます。", "accountLink.continue": "以下の確認を完了してください。",
  "common.save": "保存", "common.confirm": "確認", "kiosk.back": "キオスクに戻る", "kiosk.breakStart": "休憩開始", "kiosk.breakEnd": "休憩終了", "kiosk.code": "参加者コード", "kiosk.enterClassPin": "クラスのPINを入力", "kiosk.selectClass": "クラスを選択", "kiosk.verify": "確認", "kiosk.recorded": "アクションを記録しました",
  "members.choosePhoto": "写真を選択",
  "classes.create": "クラスを作成", "classes.edit": "クラスを編集", "classes.import": "標準グループをクラスとしてコピー", "classes.source": "コピー元のグループ", "classes.name": "クラス名", "classes.pinHint": "既存のPINを保持する場合は空欄にします。新規クラスはグループのPIN要件に従ってください。", "classes.archive": "クラスをアーカイブ", "classes.restore": "クラスを復元", "classes.delete": "クラスを完全に削除", "classes.archiveHint": "{name}をアーカイブしますか？出席履歴は保持されます。", "classes.deleteHint": "{name}を完全に削除しますか？元に戻せません。", "classes.back": "クラス一覧に戻る", "classes.search": "クラスを検索", "classes.empty": "該当するクラスはありません。",
  "account.changeEmail": "ログインメールを変更", "account.setBackup": "バックアップメールを設定", "account.removeBackup": "バックアップメールを削除", "account.removeBackupHint": "削除すると、このメールでアカウントを復旧できなくなります。", "account.pendingEmail": "確認待ち：{email}", "account.resend": "確認メールを再送", "account.cancelEmail": "保留中の変更をキャンセル", "account.verificationSent": "確認メールを送信しました。", "account.emailVerifyHint": "新しいメールアドレスに確認リンクを送信します。確認完了までは現在のアドレスが使用されます。",
  "manage.discardTitle": "変更を破棄しますか？", "manage.discardBody": "未保存の変更は失われます。", "manage.discard": "破棄", "manage.saved": "変更を保存しました。",
  "staff.create": "アカウントを作成", "staff.edit": "アカウントを編集", "staff.resetPassword": "パスワードを再設定", "staff.groupAccess": "グループアクセス", "staff.accessHint": "スタッフは選択されたグループのみ利用できます。新しいスタッフにはアクセス権がありません。",
  "staff.emailHint": "管理者は必須、スタッフは任意です。", "staff.deactivate": "無効化", "staff.activate": "再有効化", "staff.delete": "完全に削除", "staff.deleteConfirm": "{name}を完全に削除しますか？元に戻せません。", "staff.statusConfirm": "{name}のアクセスを変更しますか？無効なアカウントはログインできません。", "staff.passwordHint": "新しいパスワードを設定します。既存のパスワード強度の規則が適用されます。", "staff.search": "スタッフを検索", "staff.searchGroups": "グループを検索", "staff.accessSaved": "アクセス権を保存しました。", "staff.saveAccess": "アクセス権を保存", "staff.role": "役割",
  "security.currentPassword": "現在のパスワード", "security.newPassword": "新しいパスワード", "security.confirmPassword": "新しいパスワード（確認）", "security.changePassword": "パスワードを変更", "security.setup": "二要素認証を設定", "security.disable": "二要素認証を無効化", "security.regenerate": "リカバリーコードを再生成", "security.setupKey": "設定キー", "security.setupHint": "このキーを認証アプリに追加し、表示された6桁のコードを入力してください。", "security.recoveryCodes": "リカバリーコード", "security.codesHint": "安全な場所に保管してください。一度しか表示されません。再生成すると以前のコードは無効になります。", "security.done": "コードを保存しました", "security.code": "認証コード", "security.recoveryCode": "リカバリーコード", "security.passwordUnavailable": "この操作にはプロバイダーによる再認証が必要です。ネイティブのGoogle／Apple認証は準備中です。",
  "members.edit": "メンバーを編集", "members.save": "メンバーを保存", "members.archive": "メンバーをアーカイブ", "members.restore": "メンバーを復元", "members.archiveConfirm": "{name}をアーカイブしますか？出席履歴は保持されます。", "members.delete": "完全に削除", "members.deleteConfirm": "{name}を完全に削除しますか？元に戻せません。", "members.birthday": "生年月日", "members.dateHint": "YYYY-MM-DD形式、または空欄", "members.removePhoto": "写真を削除",
};
