# Generated by Django 5.2 for platform advertising kill switch.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_singleton(apps, schema_editor):
    PlatformAdvertisingSettings = apps.get_model(
        "core", "PlatformAdvertisingSettings"
    )
    PlatformAdvertisingSettings.objects.get_or_create(
        pk=1,
        defaults={"ads_globally_enabled": True},
    )


def unseed_singleton(apps, schema_editor):
    PlatformAdvertisingSettings = apps.get_model(
        "core", "PlatformAdvertisingSettings"
    )
    PlatformAdvertisingSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAdvertisingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ads_globally_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "When off, advertising is hidden in every workspace. "
                            "Plans and subscriptions are unchanged."
                        ),
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising",
                "verbose_name_plural": "Advertising",
            },
        ),
        migrations.AddConstraint(
            model_name="platformadvertisingsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)),
                name="core_platformadvertisingsettings_singleton_pk",
            ),
        ),
        migrations.RunPython(seed_singleton, unseed_singleton),
    ]
