# Generated by Django 5.2.17 on 2026-08-27 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_plus_yearly_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('checkstation_account_on', 'CheckStation Account ON'), ('checkstation_account_off', 'CheckStation Account OFF'), ('checkstation_plan_change', 'CheckStation plan change'), ('organization_block', 'Block organization'), ('organization_unblock', 'Unblock organization'), ('organization_permanent_delete', 'Permanently delete organization'), ('user_permanent_delete', 'Permanently delete user')], db_index=True, max_length=64)),
                ('actor_email_snapshot', models.CharField(blank=True, default='', max_length=254)),
                ('target_kind', models.CharField(blank=True, default='', max_length=32)),
                ('target_id_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('workspace_id_snapshot', models.CharField(blank=True, default='', max_length=16)),
                ('owner_email_snapshot', models.CharField(blank=True, default='', max_length=254)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform admin action',
                'verbose_name_plural': 'Platform admin actions',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='core_platfo_action__7f085b_idx')],
            },
        ),
    ]
