# Generated by Django 5.2.17 on 2026-09-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_market_aware_promotional_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpromotionmodechange',
            name='new_value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='platformpromotionmodechange',
            name='old_value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='platformpromotionsettings',
            name='business_monthly_enabled',
            field=models.BooleanField(default=False, help_text='Group 3: yearly switch offer for Business Monthly subscribers.'),
        ),
        migrations.AlterField(
            model_name='platformpromotionsettings',
            name='plus_monthly_enabled',
            field=models.BooleanField(default=False, help_text='Group 2: Plus Monthly → Plus Yearly / Business Yearly first-year offers.'),
        ),
    ]
